-- Blackwood casino, six-pair Forex economy and profession careers.
-- Apply after 20260903_inventory_equipment_tutorial.sql. Safe to re-run.

alter table public.bw_player_states add column if not exists manual numeric(14,2) not null default 10;
alter table public.bw_player_states add column if not exists intelligence numeric(14,2) not null default 10;
alter table public.bw_player_states add column if not exists endurance numeric(14,2) not null default 10;

-- CASINO --------------------------------------------------------------------
create table if not exists public.bw_casino_rounds(
 id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade,
 game text not null check(game in('blackjack','slots','roulette')), request_id uuid not null,
 bet bigint not null check(bet between 10 and 10000), payout bigint not null default 0,
 outcome jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), unique(user_id,request_id)
);
create table if not exists public.bw_blackjack_games(
 id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade,
 bet bigint not null, deck text[] not null, player_hand text[] not null, dealer_hand text[] not null,
 status text not null default 'active' check(status in('active','won','lost','push','blackjack')),
 payout bigint not null default 0, created_at timestamptz not null default now(), finished_at timestamptz
);
create unique index if not exists bw_blackjack_active_user on public.bw_blackjack_games(user_id) where status='active';
alter table public.bw_casino_rounds enable row level security; alter table public.bw_blackjack_games enable row level security;
drop policy if exists "own casino rounds" on public.bw_casino_rounds; create policy "own casino rounds" on public.bw_casino_rounds for select to authenticated using(auth.uid()=user_id);
drop policy if exists "own blackjack games" on public.bw_blackjack_games; create policy "own blackjack games" on public.bw_blackjack_games for select to authenticated using(auth.uid()=user_id);
revoke insert,update,delete on public.bw_casino_rounds,public.bw_blackjack_games from anon,authenticated;

create or replace function public.bw_card_value(p_hand text[]) returns integer language plpgsql immutable as $$
declare c text; total int:=0; aces int:=0; r text; begin foreach c in array p_hand loop r:=left(c,length(c)-1); if r='A' then total:=total+11;aces:=aces+1; elsif r in('K','Q','J') then total:=total+10; else total:=total+r::int; end if; end loop; while total>21 and aces>0 loop total:=total-10;aces:=aces-1;end loop;return total;end$$;
create or replace function public.bw_new_deck() returns text[] language sql volatile as $$
 select array_agg(r||s order by random()) from unnest(array['A','2','3','4','5','6','7','8','9','10','J','Q','K']) r cross join unnest(array['H','D','C','S']) s
$$;
create or replace function public.bw_casino_debit(p_uid uuid,p_bet bigint) returns bigint language plpgsql security definer set search_path=public,pg_temp as $$declare b bigint;begin if p_bet<10 or p_bet>10000 then raise exception 'bet must be $10–$10,000';end if;perform public.ensure_exchange_wallet(p_uid);select balance into b from public.player_wallets where user_id=p_uid for update;if b<p_bet then raise exception 'insufficient cash';end if;update public.player_wallets set balance=balance-p_bet,version=version+1,updated_at=now() where user_id=p_uid returning balance into b;perform public.mirror_wallet_to_save(p_uid,b);return b;end$$;
create or replace function public.bw_casino_credit(p_uid uuid,p_amount bigint) returns bigint language plpgsql security definer set search_path=public,pg_temp as $$declare b bigint;begin update public.player_wallets set balance=balance+greatest(0,p_amount),version=version+1,updated_at=now() where user_id=p_uid returning balance into b;perform public.mirror_wallet_to_save(p_uid,b);return b;end$$;

create or replace function public.bw_blackjack_view(p_uid uuid) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$declare g public.bw_blackjack_games;begin select * into g from public.bw_blackjack_games where user_id=p_uid order by created_at desc limit 1;if g.id is null then return null;end if;return jsonb_build_object('id',g.id,'bet',g.bet,'player',g.player_hand,'dealer',case when g.status='active' then array[g.dealer_hand[1],'??'] else g.dealer_hand end,'player_value',public.bw_card_value(g.player_hand),'dealer_value',case when g.status='active' then null else public.bw_card_value(g.dealer_hand) end,'status',g.status,'payout',g.payout,'message',case g.status when 'active' then 'Hit or stand.' when 'won' then 'You beat the dealer.' when 'lost' then 'The house wins.' when 'push' then 'Push. Your stake was returned.' else 'Blackjack pays 3:2.' end);end$$;
create or replace function public.bw_casino_snapshot() returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$declare uid uuid:=public.bw_uid();w public.player_wallets;begin w:=public.ensure_exchange_wallet(uid);return jsonb_build_object('balance',w.balance,'blackjack',public.bw_blackjack_view(uid));end$$;
create or replace function public.bw_blackjack_start(p_bet bigint,p_request_id uuid) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$declare uid uuid:=public.bw_uid();d text[];ph text[];dh text[];g public.bw_blackjack_games;v_payout bigint:=0;begin if exists(select 1 from public.bw_blackjack_games where user_id=uid and status='active') then raise exception 'finish your active hand first';end if;if exists(select 1 from public.bw_casino_rounds where user_id=uid and request_id=p_request_id) then return public.bw_casino_snapshot();end if;perform public.bw_casino_debit(uid,p_bet);d:=public.bw_new_deck();ph:=array[d[1],d[3]];dh:=array[d[2],d[4]];d:=d[5:52];insert into public.bw_blackjack_games(user_id,bet,deck,player_hand,dealer_hand) values(uid,p_bet,d,ph,dh) returning * into g;if public.bw_card_value(ph)=21 then v_payout:=floor(p_bet*2.5);update public.bw_blackjack_games set status='blackjack',payout=v_payout,finished_at=now() where id=g.id;perform public.bw_casino_credit(uid,v_payout);insert into public.bw_casino_rounds(user_id,game,request_id,bet,payout,outcome) values(uid,'blackjack',p_request_id,p_bet,v_payout,jsonb_build_object('result','blackjack'));end if;return public.bw_casino_snapshot();end$$;
create or replace function public.bw_blackjack_action(p_action text) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$declare uid uuid:=public.bw_uid();g public.bw_blackjack_games;pv int;dv int;v_payout bigint:=0;result text;begin if p_action not in('hit','stand') then raise exception 'invalid action';end if;select * into g from public.bw_blackjack_games where user_id=uid and status='active' for update;if g.id is null then raise exception 'no active hand';end if;if p_action='hit' then g.player_hand:=array_append(g.player_hand,g.deck[1]);g.deck:=g.deck[2:array_length(g.deck,1)];pv:=public.bw_card_value(g.player_hand);if pv>21 then result:='lost';else update public.bw_blackjack_games set player_hand=g.player_hand,deck=g.deck where id=g.id;return public.bw_casino_snapshot();end if;else pv:=public.bw_card_value(g.player_hand);while public.bw_card_value(g.dealer_hand)<17 loop g.dealer_hand:=array_append(g.dealer_hand,g.deck[1]);g.deck:=g.deck[2:array_length(g.deck,1)];end loop;dv:=public.bw_card_value(g.dealer_hand);if dv>21 or pv>dv then result:='won';v_payout:=g.bet*2;elsif pv=dv then result:='push';v_payout:=g.bet;else result:='lost';end if;end if;update public.bw_blackjack_games set player_hand=g.player_hand,dealer_hand=g.dealer_hand,deck=g.deck,status=result,payout=v_payout,finished_at=now() where id=g.id;if v_payout>0 then perform public.bw_casino_credit(uid,v_payout);end if;insert into public.bw_casino_rounds(user_id,game,request_id,bet,payout,outcome) values(uid,'blackjack',gen_random_uuid(),g.bet,v_payout,jsonb_build_object('result',result));return public.bw_casino_snapshot();end$$;
create or replace function public.bw_slots_spin(p_bet bigint,p_request_id uuid) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$declare uid uuid:=public.bw_uid();reels text[];payout bigint:=0;mult int:=0;b bigint;v_old public.bw_casino_rounds;begin select * into v_old from public.bw_casino_rounds where user_id=uid and request_id=p_request_id;if v_old.id is not null then select balance into b from public.player_wallets where user_id=uid;return jsonb_build_object('balance',b,'result',v_old.outcome||jsonb_build_object('payout',v_old.payout,'message','This spin was already settled.'));end if;perform public.bw_casino_debit(uid,p_bet);reels:=array[(array['♛','7','◆','BAR','●'])[1+floor(random()*5)::int],(array['♛','7','◆','BAR','●'])[1+floor(random()*5)::int],(array['♛','7','◆','BAR','●'])[1+floor(random()*5)::int]];if reels[1]=reels[2] and reels[2]=reels[3] then mult:=case reels[1] when '7' then 20 when '♛' then 12 when 'BAR' then 8 else 5 end;elsif (select count(*) from unnest(reels)x where x='●')>=2 then mult:=2;end if;payout:=p_bet*mult;if payout>0 then b:=public.bw_casino_credit(uid,payout);else select balance into b from public.player_wallets where user_id=uid;end if;insert into public.bw_casino_rounds(user_id,game,request_id,bet,payout,outcome) values(uid,'slots',p_request_id,p_bet,payout,jsonb_build_object('reels',reels,'multiplier',mult));return jsonb_build_object('balance',b,'result',jsonb_build_object('reels',reels,'payout',payout,'message',case when payout>0 then 'The machine pays '||payout else 'No winning line.' end));end$$;
create or replace function public.bw_roulette_spin(p_bet bigint,p_bet_type text,p_number int,p_request_id uuid) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$declare uid uuid:=public.bw_uid();n int:=floor(random()*37);reds int[]:=array[1,3,5,7,9,12,14,16,18,19,21,23,25,27,30,32,34,36];win bool:=false;mult int:=0;payout bigint:=0;b bigint;begin if p_bet_type not in('red','black','odd','even','low','high','straight') then raise exception 'invalid roulette bet';end if;if p_bet_type='straight' and (p_number is null or p_number<0 or p_number>36) then raise exception 'choose 0–36';end if;perform public.bw_casino_debit(uid,p_bet);win:=case p_bet_type when 'red' then n=any(reds) when 'black' then n>0 and not n=any(reds) when 'odd' then n>0 and n%2=1 when 'even' then n>0 and n%2=0 when 'low' then n between 1 and 18 when 'high' then n between 19 and 36 else n=p_number end;mult:=case when not win then 0 when p_bet_type='straight' then 36 else 2 end;payout:=p_bet*mult;if payout>0 then b:=public.bw_casino_credit(uid,payout);else select balance into b from public.player_wallets where user_id=uid;end if;insert into public.bw_casino_rounds(user_id,game,request_id,bet,payout,outcome) values(uid,'roulette',p_request_id,p_bet,payout,jsonb_build_object('number',n,'bet_type',p_bet_type,'win',win));return jsonb_build_object('balance',b,'result',jsonb_build_object('number',n,'payout',payout,'message',case when win then 'Winner. The table pays '||payout else 'The wheel lands on '||n||'.' end));end$$;

-- FOREX ---------------------------------------------------------------------
create table if not exists public.bw_fx_pairs(symbol text primary key,name text not null,digits int not null,base_price numeric(18,6) not null,spread numeric(18,6) not null,volatility numeric(10,8) not null,sort_order int not null);
insert into public.bw_fx_pairs values ('EUR/USD','Euro / US Dollar',5,1.16800,.00016,.00090,1),('GBP/USD','Pound / US Dollar',5,1.34900,.00022,.00110,2),('USD/JPY','US Dollar / Yen',3,147.200,.018,.00085,3),('AUD/USD','Australian Dollar / US Dollar',5,.65300,.00020,.00105,4),('USD/CAD','US Dollar / Canadian Dollar',5,1.37800,.00020,.00075,5),('USD/CHF','US Dollar / Swiss Franc',5,.80200,.00018,.00080,6) on conflict(symbol) do update set name=excluded.name,digits=excluded.digits,spread=excluded.spread,volatility=excluded.volatility,sort_order=excluded.sort_order;
create table if not exists public.bw_fx_quotes(symbol text primary key references public.bw_fx_pairs(symbol),mid numeric(18,6) not null,bid numeric(18,6) not null,ask numeric(18,6) not null,sequence bigint not null default 1,updated_at timestamptz not null default now());
insert into public.bw_fx_quotes(symbol,mid,bid,ask) select symbol,base_price,base_price-spread/2,base_price+spread/2 from public.bw_fx_pairs on conflict do nothing;
create table if not exists public.bw_fx_candles(symbol text not null references public.bw_fx_pairs(symbol),bucket_at timestamptz not null,open numeric(18,6),high numeric(18,6),low numeric(18,6),close numeric(18,6),primary key(symbol,bucket_at));
create table if not exists public.bw_fx_positions(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,symbol text not null references public.bw_fx_pairs(symbol),side text not null check(side in('buy','sell')),margin bigint not null check(margin>=100),leverage smallint not null check(leverage in(1,3,5,10)),entry_price numeric(18,6) not null,status text not null default 'open' check(status in('open','closed','liquidated')),exit_price numeric(18,6),pnl bigint,request_id uuid not null,opened_at timestamptz not null default now(),closed_at timestamptz,unique(user_id,request_id));
create table if not exists public.bw_fx_trader_profiles(user_id uuid primary key references auth.users(id) on delete cascade,closed_trades int not null default 0,winning_trades int not null default 0,realized_pnl bigint not null default 0,peak_equity bigint not null default 0,max_drawdown bigint not null default 0,rank text not null default 'Novice',bank_offer_unlocked bool not null default false,updated_at timestamptz not null default now());
alter table public.bw_fx_pairs enable row level security;alter table public.bw_fx_quotes enable row level security;alter table public.bw_fx_candles enable row level security;alter table public.bw_fx_positions enable row level security;alter table public.bw_fx_trader_profiles enable row level security;
drop policy if exists "read fx pairs" on public.bw_fx_pairs;create policy "read fx pairs" on public.bw_fx_pairs for select to authenticated using(true);drop policy if exists "read fx quotes" on public.bw_fx_quotes;create policy "read fx quotes" on public.bw_fx_quotes for select to authenticated using(true);drop policy if exists "read fx candles" on public.bw_fx_candles;create policy "read fx candles" on public.bw_fx_candles for select to authenticated using(true);drop policy if exists "own fx positions" on public.bw_fx_positions;create policy "own fx positions" on public.bw_fx_positions for select to authenticated using(auth.uid()=user_id);drop policy if exists "own fx profile" on public.bw_fx_trader_profiles;create policy "own fx profile" on public.bw_fx_trader_profiles for select to authenticated using(auth.uid()=user_id);
revoke insert,update,delete on public.bw_fx_pairs,public.bw_fx_quotes,public.bw_fx_candles,public.bw_fx_positions,public.bw_fx_trader_profiles from anon,authenticated;
create or replace function public.bw_fx_tick(p_symbol text) returns void language plpgsql security definer set search_path=public,pg_temp as $$declare q public.bw_fx_quotes;p public.bw_fx_pairs;n numeric;b timestamptz:=date_trunc('minute',now());begin select * into q from public.bw_fx_quotes where symbol=p_symbol for update;if q.symbol is null or q.updated_at>now()-interval '3 seconds' then return;end if;select * into p from public.bw_fx_pairs where symbol=p_symbol;n:=greatest(p.base_price*.55,least(p.base_price*1.55,q.mid*(1+((random()+random()+random())-1.5)*p.volatility)));update public.bw_fx_quotes set mid=n,bid=n-p.spread/2,ask=n+p.spread/2,sequence=sequence+1,updated_at=now() where symbol=p_symbol;insert into public.bw_fx_candles(symbol,bucket_at,open,high,low,close) values(p_symbol,b,n,n,n,n) on conflict(symbol,bucket_at) do update set high=greatest(bw_fx_candles.high,excluded.high),low=least(bw_fx_candles.low,excluded.low),close=excluded.close;delete from public.bw_fx_candles where bucket_at<now()-interval '2 days';end$$;

-- Supabase Cron advances every market even when no player has the app open.
create extension if not exists pg_cron with schema extensions;
do $$begin if not exists(select 1 from cron.job where jobname='blackwood-fx-market')then perform cron.schedule('blackwood-fx-market','* * * * *',$cron$select public.bw_fx_tick(symbol) from public.bw_fx_pairs$cron$);end if;end$$;
create or replace function public.bw_fx_mark_pnl(p public.bw_fx_positions,q numeric) returns bigint language sql immutable as $$select round(p.margin*p.leverage*(case when p.side='buy' then q/p.entry_price-1 else p.entry_price/q-1 end))::bigint$$;
create or replace function public.bw_fx_snapshot(p_symbol text default 'EUR/USD') returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$declare uid uuid:=public.bw_uid();w public.player_wallets;pr public.bw_fx_trader_profiles;q public.bw_fx_quotes;begin perform public.bw_fx_tick(p_symbol);w:=public.ensure_exchange_wallet(uid);insert into public.bw_fx_trader_profiles(user_id,peak_equity) values(uid,w.balance) on conflict do nothing;select * into pr from public.bw_fx_trader_profiles where user_id=uid;select * into q from public.bw_fx_quotes where symbol=p_symbol;return jsonb_build_object('balance',w.balance,'quote',to_jsonb(q)||(select jsonb_build_object('digits',digits) from public.bw_fx_pairs where symbol=p_symbol),'pairs',(select jsonb_agg(to_jsonb(p)||jsonb_build_object('mid',x.mid) order by p.sort_order) from public.bw_fx_pairs p join public.bw_fx_quotes x using(symbol)),'candles',coalesce((select jsonb_agg(to_jsonb(c) order by bucket_at) from(select * from public.bw_fx_candles where symbol=p_symbol order by bucket_at desc limit 60)c),'[]'::jsonb),'positions',coalesce((select jsonb_agg(to_jsonb(x)||jsonb_build_object('current_price',case when x.side='buy' then z.bid else z.ask end,'unrealized_pnl',public.bw_fx_mark_pnl(x,case when x.side='buy' then z.bid else z.ask end)) order by opened_at desc) from public.bw_fx_positions x join public.bw_fx_quotes z using(symbol) where x.user_id=uid and x.status='open'),'[]'::jsonb),'profile',to_jsonb(pr)||jsonb_build_object('next_rank_hint',case pr.rank when 'Novice' then 'Close 5 trades to become Clerk.' when 'Clerk' then 'Close 15 trades with positive P&L to become Analyst.' when 'Analyst' then 'A disciplined record unlocks Federal Trust.' else 'Protect your capital and keep trading.' end));end$$;
create or replace function public.bw_fx_open(p_symbol text,p_side text,p_margin bigint,p_leverage smallint,p_request_id uuid) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$declare uid uuid:=public.bw_uid();q public.bw_fx_quotes;entry numeric;begin if p_side not in('buy','sell') or p_leverage not in(1,3,5,10) or p_margin<100 then raise exception 'invalid order';end if;if exists(select 1 from public.bw_fx_positions where user_id=uid and request_id=p_request_id) then return public.bw_fx_snapshot(p_symbol);end if;perform public.bw_fx_tick(p_symbol);select * into q from public.bw_fx_quotes where symbol=p_symbol;if q.symbol is null then raise exception 'unknown currency pair';end if;perform public.bw_casino_debit(uid,p_margin);entry:=case when p_side='buy' then q.ask else q.bid end;insert into public.bw_fx_positions(user_id,symbol,side,margin,leverage,entry_price,request_id)values(uid,p_symbol,p_side,p_margin,p_leverage,entry,p_request_id);return public.bw_fx_snapshot(p_symbol);end$$;
create or replace function public.bw_fx_close(p_position_id uuid,p_request_id uuid) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$declare uid uuid:=public.bw_uid();p public.bw_fx_positions;q public.bw_fx_quotes;exit numeric;gain bigint;profit bigint;pr public.bw_fx_trader_profiles;begin select * into p from public.bw_fx_positions where id=p_position_id and user_id=uid for update;if p.id is null then raise exception 'position not found';end if;if p.status<>'open' then return public.bw_fx_snapshot(p.symbol);end if;perform public.bw_fx_tick(p.symbol);select * into q from public.bw_fx_quotes where symbol=p.symbol;exit:=case when p.side='buy' then q.bid else q.ask end;profit:=public.bw_fx_mark_pnl(p,exit);gain:=greatest(0,p.margin+profit);update public.bw_fx_positions set status=case when gain=0 then 'liquidated' else 'closed' end,exit_price=exit,pnl=profit,closed_at=now() where id=p.id;perform public.bw_casino_credit(uid,gain);insert into public.bw_fx_trader_profiles(user_id)values(uid)on conflict do nothing;update public.bw_fx_trader_profiles set closed_trades=closed_trades+1,winning_trades=winning_trades+(profit>0)::int,realized_pnl=realized_pnl+profit,peak_equity=greatest(peak_equity,realized_pnl+profit),max_drawdown=greatest(max_drawdown,peak_equity-(realized_pnl+profit)),updated_at=now() where user_id=uid returning * into pr;update public.bw_fx_trader_profiles set rank=case when closed_trades>=75 and realized_pnl>50000 then 'Market Maker' when closed_trades>=40 and realized_pnl>15000 then 'Senior Trader' when closed_trades>=25 and realized_pnl>5000 then 'Dealer' when closed_trades>=15 and realized_pnl>0 then 'Analyst' when closed_trades>=5 then 'Clerk' else 'Novice' end,bank_offer_unlocked=(closed_trades>=20 and realized_pnl>0 and max_drawdown<greatest(5000,abs(realized_pnl)*2)) where user_id=uid;return public.bw_fx_snapshot(p.symbol);end$$;

-- PROFESSIONS ---------------------------------------------------------------
create table if not exists public.bw_professions(id text primary key,name text not null,company text not null,description text not null,offer_only bool not null default false,sort_order int not null);
insert into public.bw_professions values('docks','Docks & Logistics','Blackwood & Sons Shipping','Manual work, freight and quiet favors.',false,1),('casino','Casino Operations','Rossi Social Club','Hospitality, surveillance and virtual gaming operations.',false,2),('medical','Medical','St. Mercy Hospital','Patient care and emergency medicine.',false,3),('education','Education','Blackwood College','Teaching, research and academic influence.',false,4),('law','Civic Law','Vale & Cross','Clerical work, litigation and city law.',false,5),('banking','Treasury & Markets','Federal Trust','An invitation-only currency and markets career.',true,6) on conflict(id) do update set name=excluded.name,company=excluded.company,description=excluded.description,offer_only=excluded.offer_only,sort_order=excluded.sort_order;
create table if not exists public.bw_job_positions(id text primary key,profession_id text not null references public.bw_professions(id),tier int not null,name text not null,daily_pay int not null,point_gain int not null,manual_gain numeric not null,intelligence_gain numeric not null,endurance_gain numeric not null,manual_required numeric not null,intelligence_required numeric not null,endurance_required numeric not null,promotion_cost int not null,special_name text not null,unique(profession_id,tier));
insert into public.bw_job_positions values
('docks-1','docks',1,'Freight Porter',700,3,2,.2,1,0,0,0,0,'Claim contraband'),('docks-2','docks',2,'Manifest Clerk',1800,5,2,1,1,30,20,25,25,'Claim contraband'),('docks-3','docks',3,'Harbor Foreman',5200,8,3,2,2,80,55,70,60,'Claim contraband'),
('casino-1','casino',1,'Floor Attendant',800,3,.5,1.5,1,0,0,0,0,'Collect house tips'),('casino-2','casino',2,'Pit Supervisor',2200,5,1,2,1.5,25,35,25,25,'Collect house tips'),('casino-3','casino',3,'Gaming Director',6000,9,1,3,2,60,90,65,65,'Collect house tips'),
('medical-1','medical',1,'Hospital Orderly',750,3,1,1,2,0,0,0,0,'Medical supplies'),('medical-2','medical',2,'Ward Nurse',2400,5,1,3,2,25,45,45,30,'Medical supplies'),('medical-3','medical',3,'Trauma Surgeon',7500,10,.5,5,2,50,125,90,80,'Medical supplies'),
('education-1','education',1,'Teaching Assistant',700,3,.3,2,.7,0,0,0,0,'Private study'),('education-2','education',2,'Lecturer',2300,5,.5,3,1,15,55,30,30,'Private study'),('education-3','education',3,'Dean',6500,9,.5,5,1.5,35,130,70,75,'Private study'),
('law-1','law',1,'Court Clerk',850,3,.5,1.5,1,0,0,0,0,'Legal intervention'),('law-2','law',2,'Paralegal',2600,5,.5,3,1.5,20,55,35,30,'Legal intervention'),('law-3','law',3,'Senior Counsel',8000,10,.5,5,2,40,135,75,80,'Legal intervention'),
('banking-1','banking',1,'Currency Analyst',3000,5,.2,3,1,0,40,20,0,'Market brief'),('banking-2','banking',2,'FX Dealer',7000,8,.2,4,1.5,15,100,55,50,'Market brief'),('banking-3','banking',3,'Managing Director',16000,12,.2,6,2,30,190,100,100,'Market brief')
on conflict(id) do update set name=excluded.name,daily_pay=excluded.daily_pay,point_gain=excluded.point_gain,manual_gain=excluded.manual_gain,intelligence_gain=excluded.intelligence_gain,endurance_gain=excluded.endurance_gain,manual_required=excluded.manual_required,intelligence_required=excluded.intelligence_required,endurance_required=excluded.endurance_required,promotion_cost=excluded.promotion_cost,special_name=excluded.special_name;
create table if not exists public.bw_job_questions(id text primary key,profession_id text not null references public.bw_professions(id),question text not null,options jsonb not null,correct_index int not null,sort_order int not null);
insert into public.bw_job_questions values
('d1','docks','A crate is missing from the manifest. What comes first?','["Report the discrepancy","Ignore it","Take another crate"]',0,1),('d2','docks','A load is too heavy to lift safely.','["Ask for equipment","Rush it","Leave the shift"]',0,2),('d3','docks','What keeps a port moving?','["Accurate timing","Rumors","Luck"]',0,3),
('c1','casino','A guest disputes a payout.','["Check the recorded result","Argue","Pay anything asked"]',0,1),('c2','casino','You notice a marked card.','["Secure it and alert the pit","Use it","Ignore it"]',0,2),('c3','casino','The house depends on…','["Consistent rules","Changing odds mid-game","Unlogged cash"]',0,3),
('m1','medical','A patient collapses.','["Assess airway and call help","Finish paperwork","Walk away"]',0,1),('m2','medical','Records are confidential.','["Yes","Only for friends","Never"]',0,2),('m3','medical','Medication dosage is unclear.','["Verify before administering","Guess","Double it"]',0,3),
('e1','education','A student challenges an answer.','["Review the evidence","Punish them","End class"]',0,1),('e2','education','Good research should be…','["Reproducible","Secret","Unquestioned"]',0,2),('e3','education','A source looks unreliable.','["Verify it","Cite it anyway","Delete the project"]',0,3),
('l1','law','A filing deadline is today.','["File and confirm receipt","Wait","Alter the date"]',0,1),('l2','law','Client information is…','["Confidential","Public gossip","For sale"]',0,2),('l3','law','Evidence must be…','["Preserved","Improved","Hidden"]',0,3),
('b1','banking','A position moves against its limit.','["Close or reduce risk","Double indefinitely","Hide it"]',0,1),('b2','banking','Client orders require…','["Accurate records","Memory only","No confirmation"]',0,2),('b3','banking','First duty of a trader?','["Protect capital","Chase every move","Guarantee profit"]',0,3)
on conflict(id) do update set question=excluded.question,options=excluded.options,correct_index=excluded.correct_index;
create table if not exists public.bw_job_interviews(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,profession_id text not null references public.bw_professions(id),status text not null default 'open',created_at timestamptz not null default now(),completed_at timestamptz);
create table if not exists public.bw_job_careers(user_id uuid primary key references auth.users(id) on delete cascade,profession_id text not null references public.bw_professions(id),position_id text not null references public.bw_job_positions(id),job_points int not null default 5,last_shift_at timestamptz,last_special_at timestamptz,started_at timestamptz not null default now());
alter table public.bw_job_interviews enable row level security;alter table public.bw_job_careers enable row level security;drop policy if exists "own interviews" on public.bw_job_interviews;create policy "own interviews" on public.bw_job_interviews for select to authenticated using(auth.uid()=user_id);drop policy if exists "own career" on public.bw_job_careers;create policy "own career" on public.bw_job_careers for select to authenticated using(auth.uid()=user_id);revoke insert,update,delete on public.bw_job_interviews,public.bw_job_careers from anon,authenticated;

create or replace function public.bw_job_snapshot() returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$declare uid uuid:=public.bw_uid();s public.bw_player_states;c public.bw_job_careers;i public.bw_job_interviews;begin s:=public.bw_refresh_player(uid);select * into c from public.bw_job_careers where user_id=uid;select * into i from public.bw_job_interviews where user_id=uid and status='open' order by created_at desc limit 1;return jsonb_build_object('stats',jsonb_build_object('manual',s.manual,'intelligence',s.intelligence,'endurance',s.endurance),'player',to_jsonb(s),'career',case when c.user_id is null then null else (select to_jsonb(c)||jsonb_build_object('profession_name',p.name,'position_name',j.name,'special_name',j.special_name,'shift_ready',c.last_shift_at is null or c.last_shift_at<now()-interval '20 hours','special_ready',c.last_special_at is null or c.last_special_at<now()-interval '24 hours')from public.bw_professions p join public.bw_job_positions j on j.id=c.position_id where p.id=c.profession_id)end,'professions',(select jsonb_agg(to_jsonb(p)||jsonb_build_object('available',not p.offer_only or coalesce((select bank_offer_unlocked from public.bw_fx_trader_profiles where user_id=uid),false))order by p.sort_order)from public.bw_professions p),'positions',coalesce((select jsonb_agg(to_jsonb(j)||jsonb_build_object('company',p.company,'can_promote',j.tier=(select tier+1 from public.bw_job_positions where id=c.position_id)and c.job_points>=j.promotion_cost and s.manual>=j.manual_required and s.intelligence>=j.intelligence_required and s.endurance>=j.endurance_required)order by j.tier)from public.bw_job_positions j join public.bw_professions p on p.id=j.profession_id where j.profession_id=c.profession_id),'[]'::jsonb),'interview',case when i.id is null then null else jsonb_build_object('id',i.id,'profession_name',(select name from public.bw_professions where id=i.profession_id),'questions',(select jsonb_agg(jsonb_build_object('id',q.id,'question',q.question,'options',q.options)order by q.sort_order)from public.bw_job_questions q where q.profession_id=i.profession_id))end);end$$;
create or replace function public.bw_job_begin_interview(p_profession_id text) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$declare uid uuid:=public.bw_uid();p public.bw_professions;begin if exists(select 1 from public.bw_job_careers where user_id=uid)then raise exception 'leave your current career before interviewing';end if;select * into p from public.bw_professions where id=p_profession_id;if p.id is null then raise exception 'profession not found';end if;if p.offer_only and not coalesce((select bank_offer_unlocked from public.bw_fx_trader_profiles where user_id=uid),false)then raise exception 'Federal Trust has not offered you a position';end if;if exists(select 1 from public.bw_job_interviews where user_id=uid and status='failed' and completed_at>now()-interval '24 hours')then raise exception 'you may interview again tomorrow';end if;update public.bw_job_interviews set status='abandoned',completed_at=now()where user_id=uid and status='open';insert into public.bw_job_interviews(user_id,profession_id)values(uid,p_profession_id);return public.bw_job_snapshot();end$$;
create or replace function public.bw_job_submit_interview(p_interview_id uuid,p_answers jsonb) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$declare uid uuid:=public.bw_uid();i public.bw_job_interviews;correct int;starter text;begin select * into i from public.bw_job_interviews where id=p_interview_id and user_id=uid and status='open'for update;if i.id is null then raise exception 'interview not found';end if;select count(*) into correct from public.bw_job_questions q where q.profession_id=i.profession_id and coalesce((p_answers->>q.id)::int,-1)=q.correct_index;if correct<>3 then update public.bw_job_interviews set status='failed',completed_at=now()where id=i.id;return public.bw_job_snapshot();end if;select id into starter from public.bw_job_positions where profession_id=i.profession_id and tier=1;insert into public.bw_job_careers(user_id,profession_id,position_id,job_points)values(uid,i.profession_id,starter,5);update public.bw_job_interviews set status='passed',completed_at=now()where id=i.id;return public.bw_job_snapshot();end$$;
create or replace function public.bw_job_work() returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$declare uid uuid:=public.bw_uid();c public.bw_job_careers;j public.bw_job_positions;b bigint;begin select * into c from public.bw_job_careers where user_id=uid for update;if c.user_id is null then raise exception 'you are not employed';end if;if c.last_shift_at>now()-interval '20 hours'then raise exception 'next shift is not ready';end if;select * into j from public.bw_job_positions where id=c.position_id;update public.bw_job_careers set job_points=job_points+j.point_gain,last_shift_at=now()where user_id=uid;update public.bw_player_states set manual=manual+j.manual_gain,intelligence=intelligence+j.intelligence_gain,endurance=endurance+j.endurance_gain,last_work_at=now()where user_id=uid;b:=public.bw_casino_credit(uid,j.daily_pay);insert into public.bw_action_logs(user_id,kind,summary)values(uid,'job','Completed a shift as '||j.name);return public.bw_job_snapshot();end$$;
create or replace function public.bw_job_promote(p_position_id text) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$declare uid uuid:=public.bw_uid();c public.bw_job_careers;cur public.bw_job_positions;n public.bw_job_positions;s public.bw_player_states;begin select * into c from public.bw_job_careers where user_id=uid for update;select * into cur from public.bw_job_positions where id=c.position_id;select * into n from public.bw_job_positions where id=p_position_id and profession_id=c.profession_id;if n.id is null or n.tier<>cur.tier+1 then raise exception 'invalid promotion';end if;select * into s from public.bw_player_states where user_id=uid;if c.job_points<n.promotion_cost or s.manual<n.manual_required or s.intelligence<n.intelligence_required or s.endurance<n.endurance_required then raise exception 'promotion requirements not met';end if;update public.bw_job_careers set position_id=n.id,job_points=job_points-n.promotion_cost where user_id=uid;return public.bw_job_snapshot();end$$;
create or replace function public.bw_job_special() returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$declare uid uuid:=public.bw_uid();c public.bw_job_careers;begin select * into c from public.bw_job_careers where user_id=uid for update;if c.last_special_at>now()-interval '24 hours'then raise exception 'special is still on cooldown';end if;if c.profession_id='casino'then perform public.bw_casino_credit(uid,1200);elsif c.profession_id='education'then update public.bw_player_states set intelligence=intelligence+3 where user_id=uid;elsif c.profession_id='law'then update public.bw_player_states set status='okay',status_until=null where user_id=uid and status='jail';elsif c.profession_id='banking'then update public.bw_fx_trader_profiles set realized_pnl=realized_pnl+250 where user_id=uid;else insert into public.bw_inventory(user_id,item_id,quantity)values(uid,case when c.profession_id='medical'then 'first-aid'else 'bourbon'end,1)on conflict(user_id,item_id)do update set quantity=bw_inventory.quantity+1;end if;update public.bw_job_careers set last_special_at=now()where user_id=uid;return public.bw_job_snapshot();end$$;

-- Compact, authenticated context for the Edge adviser. It contains no private data from other players.
create or replace function public.bw_adviser_context() returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$declare uid uuid:=public.bw_uid();begin return jsonb_build_object('city',public.bw_get_state(),'career',public.bw_job_snapshot(),'forex',public.bw_fx_snapshot('EUR/USD'),'loadout',public.bw_get_loadout(),'available_pages',array['home','crimes','combat','gym','work','missions','city','shop','bank','hospital','jail','property','family','chat','players','social','mail','forums','rankings','awards','inventory','economy','arcade']);end$$;

revoke all on function public.bw_card_value(text[]),public.bw_new_deck(),public.bw_casino_debit(uuid,bigint),public.bw_casino_credit(uuid,bigint),public.bw_blackjack_view(uuid),public.bw_casino_snapshot(),public.bw_blackjack_start(bigint,uuid),public.bw_blackjack_action(text),public.bw_slots_spin(bigint,uuid),public.bw_roulette_spin(bigint,text,int,uuid),public.bw_fx_tick(text),public.bw_fx_mark_pnl(public.bw_fx_positions,numeric),public.bw_fx_snapshot(text),public.bw_fx_open(text,text,bigint,smallint,uuid),public.bw_fx_close(uuid,uuid),public.bw_job_snapshot(),public.bw_job_begin_interview(text),public.bw_job_submit_interview(uuid,jsonb),public.bw_job_work(),public.bw_job_promote(text),public.bw_job_special(),public.bw_adviser_context() from public,anon;
grant execute on function public.bw_casino_snapshot(),public.bw_blackjack_start(bigint,uuid),public.bw_blackjack_action(text),public.bw_slots_spin(bigint,uuid),public.bw_roulette_spin(bigint,text,int,uuid),public.bw_fx_tick(text),public.bw_fx_snapshot(text),public.bw_fx_open(text,text,bigint,smallint,uuid),public.bw_fx_close(uuid,uuid),public.bw_job_snapshot(),public.bw_job_begin_interview(text),public.bw_job_submit_interview(uuid,jsonb),public.bw_job_work(),public.bw_job_promote(text),public.bw_job_special(),public.bw_adviser_context() to authenticated;
