-- Blackwood Families 2.0: headquarters, applications, shared resources,
-- organized operations, chains, ranked wars and territory income.
-- Apply after 20260904_casino_economy_careers.sql. Safe to re-run.

alter table public.runner_crews add column if not exists respect bigint not null default 0;
alter table public.runner_crews add column if not exists rating integer not null default 1000;
alter table public.runner_crews add column if not exists vault bigint not null default 0;
alter table public.runner_crews add column if not exists announcement text not null default 'Build the family. Own the city.';
alter table public.runner_crews add column if not exists chain_count integer not null default 0;
alter table public.runner_crews add column if not exists chain_expires_at timestamptz;
alter table public.runner_crews add column if not exists war_queue boolean not null default false;
alter table public.runner_crews add column if not exists wars_won integer not null default 0;
alter table public.runner_crews add column if not exists wars_lost integer not null default 0;
alter table public.runner_crews add column if not exists last_income_at timestamptz;
alter table public.runner_crew_members add column if not exists operations_joined integer not null default 0;
alter table public.runner_crew_members add column if not exists war_hits integer not null default 0;
alter table public.runner_crew_members add column if not exists last_active_at timestamptz not null default now();

create table if not exists public.bw_family_applications (
  id bigserial primary key, crew_id uuid not null references public.runner_crews(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade, message text not null default '',
  status text not null default 'pending' check(status in('pending','accepted','declined','withdrawn')),
  created_at timestamptz not null default now(), decided_at timestamptz, decided_by uuid references auth.users(id),
  unique(crew_id,user_id)
);
create table if not exists public.bw_family_logs (
  id bigserial primary key, crew_id uuid not null references public.runner_crews(id) on delete cascade,
  actor_id uuid references auth.users(id) on delete set null, kind text not null, summary text not null,
  data jsonb not null default '{}'::jsonb, created_at timestamptz not null default now()
);
create table if not exists public.bw_family_chat (
  id bigserial primary key, crew_id uuid not null references public.runner_crews(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  channel text not null default 'family' check(channel in('family','war')),
  body text not null check(char_length(body) between 1 and 500), created_at timestamptz not null default now()
);
create table if not exists public.bw_family_vault_ledger (
  id bigserial primary key, crew_id uuid not null references public.runner_crews(id) on delete cascade,
  user_id uuid references auth.users(id) on delete set null, direction text not null check(direction in('deposit','withdraw','income','operation','war')),
  amount bigint not null check(amount>0), note text not null default '', created_at timestamptz not null default now()
);
create table if not exists public.bw_family_armory (
  crew_id uuid not null references public.runner_crews(id) on delete cascade,
  item_id text not null references public.bw_items(id), quantity integer not null default 0 check(quantity>=0),
  updated_at timestamptz not null default now(), primary key(crew_id,item_id)
);
create table if not exists public.bw_family_operation_templates (
  id text primary key, name text not null, description text not null, min_members integer not null check(min_members between 2 and 12),
  duration_minutes integer not null, cash_reward bigint not null, respect_reward integer not null, roles text[] not null,
  sort_order integer not null default 0
);
insert into public.bw_family_operation_templates(id,name,description,min_members,duration_minutes,cash_reward,respect_reward,roles,sort_order) values
('dockside-lift','Dockside Lift','Intercept a bonded shipment before the harbor patrol arrives.',2,30,24000,15,array['driver','enforcer'],1),
('numbers-network','Numbers Network','Coordinate collectors, runners and the book across three boroughs.',3,60,72000,35,array['collector','runner','bookkeeper'],2),
('armored-payroll','Armored Payroll','Take the weekly payroll car with a timed street blockade.',4,120,180000,75,array['planner','driver','enforcer','lookout'],3),
('federal-reserve','Federal Reserve Job','A six-person operation requiring every specialist to be ready.',6,360,600000,180,array['planner','inside','driver','safecracker','enforcer','lookout'],4)
on conflict(id) do update set name=excluded.name,description=excluded.description,min_members=excluded.min_members,duration_minutes=excluded.duration_minutes,cash_reward=excluded.cash_reward,respect_reward=excluded.respect_reward,roles=excluded.roles,sort_order=excluded.sort_order;
create table if not exists public.bw_family_operations (
  id uuid primary key default gen_random_uuid(), crew_id uuid not null references public.runner_crews(id) on delete cascade,
  template_id text not null references public.bw_family_operation_templates(id),
  status text not null default 'recruiting' check(status in('recruiting','running','completed','cancelled')),
  created_by uuid not null references auth.users(id), created_at timestamptz not null default now(),
  starts_at timestamptz, completes_at timestamptz, paid_at timestamptz
);
create unique index if not exists bw_family_one_open_operation on public.bw_family_operations(crew_id) where status in('recruiting','running');
create table if not exists public.bw_family_operation_slots (
  operation_id uuid not null references public.bw_family_operations(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade, role text not null,
  ready boolean not null default false, joined_at timestamptz not null default now(),
  primary key(operation_id,user_id), unique(operation_id,role)
);
create table if not exists public.bw_family_wars (
  id uuid primary key default gen_random_uuid(), family_a uuid not null references public.runner_crews(id) on delete cascade,
  family_b uuid not null references public.runner_crews(id) on delete cascade,
  status text not null default 'active' check(status in('active','completed','cancelled')),
  score_a integer not null default 0, score_b integer not null default 0, target_score integer not null default 25,
  winner_id uuid references public.runner_crews(id), started_at timestamptz not null default now(), ends_at timestamptz not null default now()+interval '72 hours', completed_at timestamptz,
  check(family_a<>family_b)
);
create unique index if not exists bw_family_one_active_war_a on public.bw_family_wars(family_a) where status='active';
create unique index if not exists bw_family_one_active_war_b on public.bw_family_wars(family_b) where status='active';
create table if not exists public.bw_family_war_hits (
  id bigserial primary key, war_id uuid not null references public.bw_family_wars(id) on delete cascade,
  attack_log_id bigint not null references public.bw_attack_logs(id) on delete cascade,
  attacker_id uuid not null references auth.users(id), defender_id uuid not null references auth.users(id),
  scoring_family uuid not null references public.runner_crews(id), created_at timestamptz not null default now(), unique(attack_log_id)
);
create table if not exists public.bw_territories (
  id text primary key, name text not null, district text not null, income bigint not null,
  claim_cost bigint not null, bonus text not null, sort_order integer not null default 0
);
insert into public.bw_territories(id,name,district,income,claim_cost,bonus,sort_order) values
('old-docks','Old Docks','Harbor',25000,100000,'Operations pay +5%',1),('warehouse-row','Warehouse Row','Harbor',32000,140000,'Armory prestige',2),
('little-italy','Little Italy','North Ward',40000,180000,'Family respect',3),('union-yard','Union Yard','Industrial',46000,225000,'Job influence',4),
('velvet-mile','Velvet Mile','Downtown',55000,300000,'Casino standing',5),('bankers-row','Bankers Row','Downtown',70000,425000,'Forex reputation',6),
('west-market','West Market','West End',36000,160000,'Shop connections',7),('saint-square','Saint Square','Old Town',44000,210000,'Recovery network',8),
('rail-depot','Rail Depot','Southside',52000,275000,'Crime logistics',9),('blackwood-heights','Blackwood Heights','Uptown',85000,550000,'Property prestige',10),
('civic-center','Civic Center','Central',100000,750000,'City influence',11),('federal-block','Federal Block','Central',125000,1000000,'Bank connections',12)
on conflict(id) do update set name=excluded.name,district=excluded.district,income=excluded.income,claim_cost=excluded.claim_cost,bonus=excluded.bonus,sort_order=excluded.sort_order;
create table if not exists public.bw_family_territories (
  territory_id text primary key references public.bw_territories(id) on delete cascade,
  crew_id uuid not null references public.runner_crews(id) on delete cascade,
  captured_at timestamptz not null default now()
);

alter table public.bw_family_applications enable row level security; alter table public.bw_family_logs enable row level security;
alter table public.bw_family_chat enable row level security; alter table public.bw_family_vault_ledger enable row level security;
alter table public.bw_family_armory enable row level security; alter table public.bw_family_operation_templates enable row level security;
alter table public.bw_family_operations enable row level security; alter table public.bw_family_operation_slots enable row level security;
alter table public.bw_family_wars enable row level security; alter table public.bw_family_war_hits enable row level security;
alter table public.bw_territories enable row level security; alter table public.bw_family_territories enable row level security;
do $$ declare t text; begin foreach t in array array['bw_family_applications','bw_family_logs','bw_family_chat','bw_family_vault_ledger','bw_family_armory','bw_family_operations','bw_family_operation_slots','bw_family_wars','bw_family_war_hits','bw_family_territories'] loop execute format('revoke all on public.%I from authenticated,anon',t); end loop; end $$;
grant select on public.bw_family_operation_templates,public.bw_territories to authenticated;

create or replace function public.bw_family_role(p_uid uuid default auth.uid()) returns text language sql stable security definer set search_path=public,pg_temp as $$ select role from public.runner_crew_members where user_id=p_uid $$;
create or replace function public.bw_family_id(p_uid uuid default auth.uid()) returns uuid language sql stable security definer set search_path=public,pg_temp as $$ select crew_id from public.runner_crew_members where user_id=p_uid $$;
revoke all on function public.bw_family_role(uuid),public.bw_family_id(uuid) from public,anon,authenticated;

create or replace function public.bw_family_snapshot() returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare uid uuid:=public.bw_uid(); cid uuid:=public.bw_family_id(uid); my_role text:=public.bw_family_role(uid); result jsonb;
begin
  update public.runner_crews set chain_count=0,chain_expires_at=null where id=cid and chain_expires_at<now();
  update public.bw_family_wars set status='completed',completed_at=now() where status='active' and ends_at<=now();
  select jsonb_build_object(
    'authority',true,'role',my_role,
    'directory',coalesce((select jsonb_agg(jsonb_build_object('id',c.id,'name',c.name,'tag',c.tag,'level',c.level,'respect',c.respect,'rating',c.rating,'division',case when c.rating>=1800 then 'Diamond' when c.rating>=1500 then 'Platinum' when c.rating>=1300 then 'Gold' when c.rating>=1150 then 'Silver' when c.rating>=1000 then 'Bronze' else 'Iron' end,'members',(select count(*) from public.runner_crew_members m where m.crew_id=c.id),'territories',(select count(*) from public.bw_family_territories ft where ft.crew_id=c.id)) order by c.rating desc,c.respect desc),'[]'::jsonb) from public.runner_crews c where c.visibility='public'),
    'applications',coalesce((select jsonb_agg(jsonb_build_object('id',a.id,'crewId',a.crew_id,'crewName',c.name,'userId',a.user_id,'name',p.display_name,'message',a.message,'status',a.status,'createdAt',a.created_at) order by a.created_at desc) from public.bw_family_applications a join public.runner_crews c on c.id=a.crew_id left join public.profiles p on p.id=a.user_id where (cid is null and a.user_id=uid) or (cid=a.crew_id and my_role in('leader','officer') and a.status='pending')),'[]'::jsonb),
    'family',case when cid is null then null else (select jsonb_build_object('id',c.id,'name',c.name,'tag',c.tag,'level',c.level,'xp',c.xp,'respect',c.respect,'rating',c.rating,'division',case when c.rating>=1800 then 'Diamond' when c.rating>=1500 then 'Platinum' when c.rating>=1300 then 'Gold' when c.rating>=1150 then 'Silver' when c.rating>=1000 then 'Bronze' else 'Iron' end,'vault',c.vault,'announcement',c.announcement,'chainCount',c.chain_count,'chainExpiresAt',c.chain_expires_at,'queued',c.war_queue,'warsWon',c.wars_won,'warsLost',c.wars_lost,'lastIncomeAt',c.last_income_at) from public.runner_crews c where c.id=cid) end,
    'members',coalesce((select jsonb_agg(jsonb_build_object('userId',m.user_id,'name',coalesce(p.display_name,'Associate'),'role',m.role,'contribution',m.contribution,'warHits',m.war_hits,'operations',m.operations_joined,'joinedAt',m.joined_at,'lastSeenAt',p.last_seen_at) order by case m.role when 'leader' then 0 when 'officer' then 1 else 2 end,m.contribution desc) from public.runner_crew_members m left join public.profiles p on p.id=m.user_id where m.crew_id=cid),'[]'::jsonb),
    'templates',coalesce((select jsonb_agg(to_jsonb(t) order by t.sort_order) from public.bw_family_operation_templates t),'[]'::jsonb),
    'operations',coalesce((select jsonb_agg(to_jsonb(o)||jsonb_build_object('name',t.name,'description',t.description,'minMembers',t.min_members,'durationMinutes',t.duration_minutes,'cashReward',t.cash_reward,'respectReward',t.respect_reward,'roles',t.roles,'slots',coalesce((select jsonb_agg(jsonb_build_object('userId',s.user_id,'name',p.display_name,'role',s.role,'ready',s.ready) order by s.joined_at) from public.bw_family_operation_slots s left join public.profiles p on p.id=s.user_id where s.operation_id=o.id),'[]'::jsonb)) order by o.created_at desc) from public.bw_family_operations o join public.bw_family_operation_templates t on t.id=o.template_id where o.crew_id=cid and o.status in('recruiting','running')),'[]'::jsonb),
    'war',coalesce((select jsonb_build_object('id',w.id,'status',w.status,'opponentId',case when w.family_a=cid then w.family_b else w.family_a end,'opponent',case when w.family_a=cid then b.name else a.name end,'ourScore',case when w.family_a=cid then w.score_a else w.score_b end,'theirScore',case when w.family_a=cid then w.score_b else w.score_a end,'target',w.target_score,'endsAt',w.ends_at,'hits',coalesce((select jsonb_agg(jsonb_build_object('attacker',pa.display_name,'defender',pd.display_name,'family',h.scoring_family,'createdAt',h.created_at) order by h.created_at desc) from (select * from public.bw_family_war_hits where war_id=w.id order by created_at desc limit 20) h left join public.profiles pa on pa.id=h.attacker_id left join public.profiles pd on pd.id=h.defender_id),'[]'::jsonb)) from public.bw_family_wars w join public.runner_crews a on a.id=w.family_a join public.runner_crews b on b.id=w.family_b where w.status='active' and cid in(w.family_a,w.family_b) limit 1),'null'::jsonb),
    'territories',coalesce((select jsonb_agg(to_jsonb(t)||jsonb_build_object('ownerId',ft.crew_id,'ownerName',c.name,'owned',ft.crew_id=cid) order by t.sort_order) from public.bw_territories t left join public.bw_family_territories ft on ft.territory_id=t.id left join public.runner_crews c on c.id=ft.crew_id),'[]'::jsonb),
    'armory',coalesce((select jsonb_agg(jsonb_build_object('itemId',a.item_id,'quantity',a.quantity,'name',i.name,'kind',i.kind,'slot',i.slot,'rarity',i.rarity,'attack',i.attack,'defense',i.defense) order by i.rarity desc,i.name) from public.bw_family_armory a join public.bw_items i on i.id=a.item_id where a.crew_id=cid and a.quantity>0),'[]'::jsonb),
    'inventory',coalesce((select jsonb_agg(jsonb_build_object('itemId',v.item_id,'quantity',v.quantity,'equipped',v.equipped,'name',i.name,'kind',i.kind,'slot',i.slot,'rarity',i.rarity) order by i.name) from public.bw_inventory v join public.bw_items i on i.id=v.item_id where v.user_id=uid and v.quantity>0),'[]'::jsonb),
    'chat',coalesce((select jsonb_agg(jsonb_build_object('id',x.id,'userId',x.user_id,'name',p.display_name,'channel',x.channel,'body',x.body,'createdAt',x.created_at) order by x.created_at) from (select * from public.bw_family_chat where crew_id=cid order by created_at desc limit 80)x left join public.profiles p on p.id=x.user_id),'[]'::jsonb),
    'logs',coalesce((select jsonb_agg(jsonb_build_object('id',x.id,'kind',x.kind,'summary',x.summary,'actor',p.display_name,'createdAt',x.created_at) order by x.created_at desc) from (select * from public.bw_family_logs where crew_id=cid order by created_at desc limit 40)x left join public.profiles p on p.id=x.actor_id),'[]'::jsonb)
  ) into result;
  return result;
end $$;

create or replace function public.bw_family_apply(p_crew_id uuid,p_message text default '') returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$ declare uid uuid:=public.bw_uid(); begin
  if public.bw_family_id(uid) is not null then raise exception 'already in a family'; end if;
  if not exists(select 1 from public.runner_crews where id=p_crew_id and visibility='public') then raise exception 'family unavailable'; end if;
  insert into public.bw_family_applications(crew_id,user_id,message,status,created_at,decided_at,decided_by) values(p_crew_id,uid,left(btrim(coalesce(p_message,'')),240),'pending',now(),null,null)
  on conflict(crew_id,user_id) do update set message=excluded.message,status='pending',created_at=now(),decided_at=null,decided_by=null;
  return public.bw_family_snapshot(); end $$;
create or replace function public.bw_family_decide_application(p_application_id bigint,p_accept boolean) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$ declare uid uuid:=public.bw_uid(); cid uuid:=public.bw_family_id(uid); app public.bw_family_applications; begin
  if public.bw_family_role(uid) not in('leader','officer') then raise exception 'officer permission required'; end if;
  select * into app from public.bw_family_applications where id=p_application_id and crew_id=cid and status='pending' for update;
  if app.id is null then raise exception 'application unavailable'; end if;
  if p_accept then if exists(select 1 from public.runner_crew_members where user_id=app.user_id) then raise exception 'applicant already joined a family'; end if; if (select count(*) from public.runner_crew_members where crew_id=cid)>=24 then raise exception 'family is full'; end if; insert into public.runner_crew_members(crew_id,user_id,role) values(cid,app.user_id,'runner'); end if;
  update public.bw_family_applications set status=case when p_accept then 'accepted' else 'declined' end,decided_at=now(),decided_by=uid where id=app.id;
  insert into public.bw_family_logs(crew_id,actor_id,kind,summary) values(cid,uid,'membership',case when p_accept then 'Accepted a new family member' else 'Declined an application' end);
  return public.bw_family_snapshot(); end $$;
create or replace function public.bw_family_set_role(p_user_id uuid,p_role text) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$ declare uid uuid:=public.bw_uid(); cid uuid:=public.bw_family_id(uid); begin
  if public.bw_family_role(uid)<>'leader' then raise exception 'boss permission required'; end if; if p_user_id=uid then raise exception 'the boss role cannot be changed here'; end if;
  if p_role not in('officer','runner') then raise exception 'invalid role'; end if; update public.runner_crew_members set role=p_role where crew_id=cid and user_id=p_user_id; if not found then raise exception 'member not found'; end if;
  insert into public.bw_family_logs(crew_id,actor_id,kind,summary) values(cid,uid,'role','Changed a member role to '||p_role); return public.bw_family_snapshot(); end $$;
create or replace function public.bw_family_announcement(p_announcement text) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$ declare uid uuid:=public.bw_uid(); cid uuid:=public.bw_family_id(uid); begin if public.bw_family_role(uid) not in('leader','officer') then raise exception 'officer permission required'; end if; update public.runner_crews set announcement=left(btrim(p_announcement),240),updated_at=now() where id=cid; return public.bw_family_snapshot(); end $$;
create or replace function public.bw_family_send_chat(p_channel text,p_body text) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$ declare uid uuid:=public.bw_uid(); cid uuid:=public.bw_family_id(uid); begin if cid is null then raise exception 'join a family first'; end if; if p_channel not in('family','war') then raise exception 'invalid channel'; end if; insert into public.bw_family_chat(crew_id,user_id,channel,body) values(cid,uid,p_channel,left(btrim(p_body),500)); update public.runner_crew_members set last_active_at=now() where user_id=uid; return public.bw_family_snapshot(); end $$;

create or replace function public.bw_family_vault_transfer(p_direction text,p_amount bigint) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$ declare uid uuid:=public.bw_uid(); cid uuid:=public.bw_family_id(uid); amount bigint:=greatest(1,p_amount); w public.player_wallets; begin if cid is null then raise exception 'join a family first'; end if; w:=public.ensure_exchange_wallet(uid);
  if p_direction='deposit' then if w.balance<amount then raise exception 'insufficient cash'; end if; update public.player_wallets set balance=balance-amount,version=version+1,updated_at=now() where user_id=uid; update public.runner_crews set vault=vault+amount where id=cid;
  elsif p_direction='withdraw' then if public.bw_family_role(uid) not in('leader','officer') then raise exception 'officer permission required'; end if; perform 1 from public.runner_crews where id=cid and vault>=amount for update; if not found then raise exception 'insufficient family funds'; end if; update public.runner_crews set vault=vault-amount where id=cid; update public.player_wallets set balance=balance+amount,version=version+1,updated_at=now() where user_id=uid;
  else raise exception 'invalid transfer'; end if; perform public.mirror_wallet_to_save(uid,(select balance from public.player_wallets where user_id=uid)); insert into public.bw_family_vault_ledger(crew_id,user_id,direction,amount,note) values(cid,uid,p_direction,amount,'Family vault transfer'); insert into public.bw_family_logs(crew_id,actor_id,kind,summary,data) values(cid,uid,'vault',initcap(p_direction)||'ed $'||amount,jsonb_build_object('amount',amount)); return public.bw_family_snapshot(); end $$;
create or replace function public.bw_family_armory_transfer(p_direction text,p_item_id text,p_quantity integer default 1) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$ declare uid uuid:=public.bw_uid(); cid uuid:=public.bw_family_id(uid); q integer:=greatest(1,least(100,p_quantity)); owned integer; begin if cid is null then raise exception 'join a family first'; end if;
  if p_direction='deposit' then select quantity into owned from public.bw_inventory where user_id=uid and item_id=p_item_id and not equipped for update; if coalesce(owned,0)<q then raise exception 'unequipped quantity unavailable'; end if; update public.bw_inventory set quantity=quantity-q where user_id=uid and item_id=p_item_id; delete from public.bw_inventory where user_id=uid and item_id=p_item_id and quantity=0; insert into public.bw_family_armory(crew_id,item_id,quantity) values(cid,p_item_id,q) on conflict(crew_id,item_id) do update set quantity=bw_family_armory.quantity+excluded.quantity,updated_at=now();
  elsif p_direction='withdraw' then if public.bw_family_role(uid) not in('leader','officer') then raise exception 'officer permission required'; end if; update public.bw_family_armory set quantity=quantity-q,updated_at=now() where crew_id=cid and item_id=p_item_id and quantity>=q; if not found then raise exception 'armory quantity unavailable'; end if; insert into public.bw_inventory(user_id,item_id,quantity,equipped) values(uid,p_item_id,q,false) on conflict(user_id,item_id) do update set quantity=bw_inventory.quantity+excluded.quantity;
  else raise exception 'invalid transfer'; end if; insert into public.bw_family_logs(crew_id,actor_id,kind,summary,data) values(cid,uid,'armory',initcap(p_direction)||'ed family equipment',jsonb_build_object('itemId',p_item_id,'quantity',q)); return public.bw_family_snapshot(); end $$;

create or replace function public.bw_family_create_operation(p_template_id text) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$ declare uid uuid:=public.bw_uid(); cid uuid:=public.bw_family_id(uid); oid uuid; first_role text; begin if public.bw_family_role(uid) not in('leader','officer') then raise exception 'officer permission required'; end if; select roles[1] into first_role from public.bw_family_operation_templates where id=p_template_id; if first_role is null then raise exception 'operation not found'; end if; insert into public.bw_family_operations(crew_id,template_id,created_by) values(cid,p_template_id,uid) returning id into oid; insert into public.bw_family_operation_slots(operation_id,user_id,role,ready) values(oid,uid,first_role,true); return public.bw_family_snapshot(); end $$;
create or replace function public.bw_family_join_operation(p_operation_id uuid,p_role text) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$ declare uid uuid:=public.bw_uid(); cid uuid:=public.bw_family_id(uid); allowed text[]; begin select t.roles into allowed from public.bw_family_operations o join public.bw_family_operation_templates t on t.id=o.template_id where o.id=p_operation_id and o.crew_id=cid and o.status='recruiting'; if allowed is null or not(p_role=any(allowed)) then raise exception 'operation role unavailable'; end if; insert into public.bw_family_operation_slots(operation_id,user_id,role) values(p_operation_id,uid,p_role) on conflict(operation_id,user_id) do update set role=excluded.role,ready=false; return public.bw_family_snapshot(); end $$;
create or replace function public.bw_family_ready_operation(p_operation_id uuid,p_ready boolean default true) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$ declare uid uuid:=public.bw_uid(); begin update public.bw_family_operation_slots set ready=p_ready where operation_id=p_operation_id and user_id=uid; if not found then raise exception 'join the operation first'; end if; return public.bw_family_snapshot(); end $$;
create or replace function public.bw_family_launch_operation(p_operation_id uuid) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$ declare uid uuid:=public.bw_uid(); cid uuid:=public.bw_family_id(uid); needed integer; duration integer; joined integer; ready_count integer; begin if public.bw_family_role(uid) not in('leader','officer') then raise exception 'officer permission required'; end if; select t.min_members,t.duration_minutes into needed,duration from public.bw_family_operations o join public.bw_family_operation_templates t on t.id=o.template_id where o.id=p_operation_id and o.crew_id=cid and o.status='recruiting' for update; if needed is null then raise exception 'operation unavailable'; end if; select count(*),count(*) filter(where ready) into joined,ready_count from public.bw_family_operation_slots where operation_id=p_operation_id; if joined<needed or ready_count<>joined then raise exception '% ready members required',needed; end if; update public.bw_family_operations set status='running',starts_at=now(),completes_at=now()+make_interval(mins=>duration) where id=p_operation_id; insert into public.bw_family_logs(crew_id,actor_id,kind,summary) values(cid,uid,'operation','Launched an organized operation'); return public.bw_family_snapshot(); end $$;
create or replace function public.bw_family_collect_operation(p_operation_id uuid) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$ declare uid uuid:=public.bw_uid(); cid uuid:=public.bw_family_id(uid); reward bigint; respect_gain integer; member_count integer; share bigint; participant record; begin if public.bw_family_role(uid) not in('leader','officer') then raise exception 'officer permission required'; end if; select t.cash_reward,t.respect_reward into reward,respect_gain from public.bw_family_operations o join public.bw_family_operation_templates t on t.id=o.template_id where o.id=p_operation_id and o.crew_id=cid and o.status='running' and o.completes_at<=now() for update; if reward is null then raise exception 'operation is not ready'; end if; select count(*) into member_count from public.bw_family_operation_slots where operation_id=p_operation_id; share:=floor(reward*.7/member_count); for participant in select user_id from public.bw_family_operation_slots where operation_id=p_operation_id loop perform public.ensure_exchange_wallet(participant.user_id); update public.player_wallets set balance=balance+share,version=version+1,updated_at=now() where user_id=participant.user_id; perform public.mirror_wallet_to_save(participant.user_id,(select balance from public.player_wallets where user_id=participant.user_id)); update public.runner_crew_members set operations_joined=operations_joined+1,contribution=contribution+respect_gain where user_id=participant.user_id; end loop; update public.runner_crews set vault=vault+reward-share*member_count,respect=respect+respect_gain,xp=xp+respect_gain*10 where id=cid; update public.bw_family_operations set status='completed',paid_at=now() where id=p_operation_id; insert into public.bw_family_vault_ledger(crew_id,direction,amount,note) values(cid,'operation',reward-share*member_count,'Organized operation share'); insert into public.bw_family_logs(crew_id,actor_id,kind,summary,data) values(cid,uid,'operation','Completed an organized operation',jsonb_build_object('reward',reward,'share',share)); return public.bw_family_snapshot(); end $$;

create or replace function public.bw_family_enlist_war() returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$ declare uid uuid:=public.bw_uid(); cid uuid:=public.bw_family_id(uid); rival uuid; begin if public.bw_family_role(uid)<>'leader' then raise exception 'boss permission required'; end if; if exists(select 1 from public.bw_family_wars where status='active' and cid in(family_a,family_b)) then raise exception 'family already at war'; end if; select id into rival from public.runner_crews where id<>cid and war_queue and not exists(select 1 from public.bw_family_wars where status='active' and id in(family_a,family_b)) order by abs(rating-(select rating from public.runner_crews where id=cid)),updated_at limit 1 for update skip locked; if rival is null then update public.runner_crews set war_queue=true where id=cid; insert into public.bw_family_logs(crew_id,actor_id,kind,summary) values(cid,uid,'war','Entered ranked war matchmaking'); else update public.runner_crews set war_queue=false where id in(cid,rival); insert into public.bw_family_wars(family_a,family_b) values(cid,rival); insert into public.bw_family_logs(crew_id,actor_id,kind,summary) values(cid,uid,'war','A ranked family war has begun'),(rival,null,'war','A ranked family war has begun'); end if; return public.bw_family_snapshot(); end $$;
create or replace function public.bw_family_claim_territory(p_territory_id text) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$ declare uid uuid:=public.bw_uid(); cid uuid:=public.bw_family_id(uid); cost bigint; begin if public.bw_family_role(uid) not in('leader','officer') then raise exception 'officer permission required'; end if; select claim_cost into cost from public.bw_territories where id=p_territory_id; if cost is null then raise exception 'territory not found'; end if; perform 1 from public.runner_crews where id=cid and vault>=cost for update; if not found then raise exception 'family vault needs $%',cost; end if; insert into public.bw_family_territories(territory_id,crew_id) values(p_territory_id,cid); update public.runner_crews set vault=vault-cost where id=cid; insert into public.bw_family_logs(crew_id,actor_id,kind,summary) values(cid,uid,'territory','Claimed a Blackwood territory'); return public.bw_family_snapshot(); exception when unique_violation then raise exception 'territory is already controlled'; end $$;
create or replace function public.bw_family_collect_income() returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$ declare uid uuid:=public.bw_uid(); cid uuid:=public.bw_family_id(uid); total bigint; last_claim timestamptz; begin if public.bw_family_role(uid) not in('leader','officer') then raise exception 'officer permission required'; end if; select last_income_at into last_claim from public.runner_crews where id=cid for update; if last_claim is not null and last_claim>now()-interval '20 hours' then raise exception 'territory income is not ready'; end if; select coalesce(sum(t.income),0) into total from public.bw_family_territories ft join public.bw_territories t on t.id=ft.territory_id where ft.crew_id=cid; if total=0 then raise exception 'control a territory first'; end if; update public.runner_crews set vault=vault+total,last_income_at=now() where id=cid; insert into public.bw_family_vault_ledger(crew_id,user_id,direction,amount,note) values(cid,uid,'income',total,'Territory collections'); return public.bw_family_snapshot(); end $$;

create or replace function public.bw_family_record_attack() returns trigger language plpgsql security definer set search_path=public,pg_temp as $$ declare ac uuid; dc uuid; wid uuid; a_is_a boolean; new_score integer; target integer; loser uuid; begin if new.winner_id<>new.attacker_id then return new; end if; ac:=public.bw_family_id(new.attacker_id); dc:=public.bw_family_id(new.defender_id); if ac is null or dc is null or ac=dc then return new; end if; update public.runner_crews set chain_count=case when chain_expires_at>now() then chain_count+1 else 1 end,chain_expires_at=now()+interval '5 minutes',respect=respect+1 where id=ac; update public.runner_crew_members set war_hits=war_hits+1,contribution=contribution+1,last_active_at=now() where user_id=new.attacker_id; select id,family_a=ac,target_score into wid,a_is_a,target from public.bw_family_wars where status='active' and ((family_a=ac and family_b=dc) or(family_a=dc and family_b=ac)) limit 1 for update; if wid is null then return new; end if; insert into public.bw_family_war_hits(war_id,attack_log_id,attacker_id,defender_id,scoring_family) values(wid,new.id,new.attacker_id,new.defender_id,ac) on conflict do nothing; if not found then return new; end if; if a_is_a then update public.bw_family_wars set score_a=score_a+1 where id=wid returning score_a into new_score; else update public.bw_family_wars set score_b=score_b+1 where id=wid returning score_b into new_score; end if; if new_score>=target then select case when family_a=ac then family_b else family_a end into loser from public.bw_family_wars where id=wid; update public.bw_family_wars set status='completed',winner_id=ac,completed_at=now() where id=wid; update public.runner_crews set rating=rating+50,wars_won=wars_won+1,vault=vault+100000 where id=ac; update public.runner_crews set rating=greatest(700,rating-35),wars_lost=wars_lost+1 where id=loser; insert into public.bw_family_vault_ledger(crew_id,direction,amount,note) values(ac,'war',100000,'Ranked war victory'); end if; return new; end $$;
drop trigger if exists bw_family_attack_progress on public.bw_attack_logs; create trigger bw_family_attack_progress after insert on public.bw_attack_logs for each row execute function public.bw_family_record_attack();

-- Keep the original create/leave entry points, but route their responses to Families 2.0.
create or replace function public.create_runner_crew(p_name text,p_tag text,p_color text default '#b99654') returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$ declare uid uuid:=public.bw_uid(); cid uuid; n text:=btrim(p_name); t text:=upper(btrim(p_tag)); begin if public.bw_family_id(uid) is not null then raise exception 'leave your current family first'; end if; if n!~'^[A-Za-z0-9 _-]{3,24}$' or t!~'^[A-Z0-9]{2,5}$' then raise exception 'invalid family name or tag'; end if; insert into public.runner_crews(name,tag,color,leader_id) values(n,t,case when p_color~'^#[0-9a-fA-F]{6}$' then lower(p_color) else '#b99654' end,uid) returning id into cid; insert into public.runner_crew_members(crew_id,user_id,role) values(cid,uid,'leader'); insert into public.bw_family_logs(crew_id,actor_id,kind,summary) values(cid,uid,'founded','Founded the family'); return public.bw_family_snapshot(); end $$;
create or replace function public.leave_runner_crew() returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$ declare uid uuid:=public.bw_uid(); m public.runner_crew_members; successor uuid; begin select * into m from public.runner_crew_members where user_id=uid for update; if m.user_id is null then return public.bw_family_snapshot(); end if; if exists(select 1 from public.bw_family_wars where status='active' and m.crew_id in(family_a,family_b)) then raise exception 'cannot leave during an active family war'; end if; if m.role='leader' then select user_id into successor from public.runner_crew_members where crew_id=m.crew_id and user_id<>uid order by case role when 'officer' then 0 else 1 end,joined_at limit 1; if successor is null then delete from public.runner_crews where id=m.crew_id; return public.bw_family_snapshot(); end if; update public.runner_crew_members set role='leader' where user_id=successor; update public.runner_crews set leader_id=successor where id=m.crew_id; end if; delete from public.runner_crew_members where user_id=uid; return public.bw_family_snapshot(); end $$;

create or replace function public.bw_adviser_context() returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$ declare uid uuid:=public.bw_uid(); begin return jsonb_build_object('city',public.bw_get_state(),'career',public.bw_job_snapshot(),'forex',public.bw_fx_snapshot('EUR/USD'),'loadout',public.bw_get_loadout(),'family',public.bw_family_snapshot(),'available_pages',array['home','crimes','combat','gym','work','missions','city','shop','bank','hospital','jail','property','family','chat','players','social','mail','forums','rankings','awards','inventory','economy','arcade']); end $$;

revoke all on function public.bw_family_snapshot(),public.bw_family_apply(uuid,text),public.bw_family_decide_application(bigint,boolean),public.bw_family_set_role(uuid,text),public.bw_family_announcement(text),public.bw_family_send_chat(text,text),public.bw_family_vault_transfer(text,bigint),public.bw_family_armory_transfer(text,text,integer),public.bw_family_create_operation(text),public.bw_family_join_operation(uuid,text),public.bw_family_ready_operation(uuid,boolean),public.bw_family_launch_operation(uuid),public.bw_family_collect_operation(uuid),public.bw_family_enlist_war(),public.bw_family_claim_territory(text),public.bw_family_collect_income() from public,anon;
grant execute on function public.bw_family_snapshot(),public.bw_family_apply(uuid,text),public.bw_family_decide_application(bigint,boolean),public.bw_family_set_role(uuid,text),public.bw_family_announcement(text),public.bw_family_send_chat(text,text),public.bw_family_vault_transfer(text,bigint),public.bw_family_armory_transfer(text,text,integer),public.bw_family_create_operation(text),public.bw_family_join_operation(uuid,text),public.bw_family_ready_operation(uuid,boolean),public.bw_family_launch_operation(uuid),public.bw_family_collect_operation(uuid),public.bw_family_enlist_war(),public.bw_family_claim_territory(text),public.bw_family_collect_income() to authenticated;
revoke execute on function public.join_runner_crew(uuid) from authenticated;
grant execute on function public.create_runner_crew(text,text,text),public.leave_runner_crew(),public.bw_adviser_context() to authenticated;

do $$ begin
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='bw_family_chat') then alter publication supabase_realtime add table public.bw_family_chat; end if;
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='bw_family_wars') then alter publication supabase_realtime add table public.bw_family_wars; end if;
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='bw_family_operations') then alter publication supabase_realtime add table public.bw_family_operations; end if;
end $$;
