import { useCallback, useEffect, useMemo, useState } from "react";
import { supabase } from "../online/supabase.js";
import GameIcon from "../ui/GameIcon.jsx";
import "./progression.css";

const tabs = [["story","Story"],["factions","Factions"],["standing","Standing"],["combat","Combat mastery"]];
const money = value => `$${Number(value || 0).toLocaleString()}`;
const id = () => crypto.randomUUID();
const pct = (value,max) => Math.min(100,Number(value || 0)/Math.max(1,Number(max || 1))*100);
function Meter({value,max}) { return <figure className="progress-meter"><i style={{width:`${pct(value,max)}%`}}/></figure>; }

export default function ProgressionHub({onState}) {
  const [data,setData]=useState(null),[tab,setTab]=useState("story"),[busy,setBusy]=useState(false),[error,setError]=useState(""),[result,setResult]=useState(null),[cooldown,setCooldown]=useState(0);
  const load=useCallback(async()=>{const{data:value,error:problem}=await supabase.rpc("bw_progression_snapshot");if(problem)setError(problem.message);else{setData(value);setError("");onState?.(value?.player)}},[onState]);
  useEffect(()=>{load()},[load]);
  useEffect(()=>{if(!cooldown)return;const timer=setInterval(()=>setCooldown(value=>Math.max(0,value-1)),1000);return()=>clearInterval(timer)},[cooldown]);
  const act=async(rpc,params={})=>{if(busy)return;setBusy(true);setError("");const{data:value,error:problem}=await supabase.rpc(rpc,params);if(problem)setError(problem.message);else{const next=value?.progression||value;setData(next);setResult(value?.event||null);onState?.(next?.player)}setBusy(false)};
  const chapters=useMemo(()=>Object.values((data?.missions||[]).reduce((all,mission)=>{(all[mission.chapter]??={chapter:mission.chapter,missions:[]}).missions.push(mission);return all},{})),[data]);
  if(error&&!data)return <div className="progress-install"><b>Progression expansion needs installing</b><p>Run <code>supabase/20260915_core_rpg_progression.sql</code> in Supabase, then retry.</p><button onClick={load}>Retry</button><small>{error}</small></div>;
  if(!data)return <div className="progress-loading">Opening the Blackwood campaign ledger…</div>;
  const rank=data.rank||{},grind=data.grind||{},combat=data.combat||{};
  return <div className="progression-hub">
    <section className="standing-hero"><div><small>CITY CAMPAIGN · SERVER VERIFIED</small><h2>{rank.name}</h2><p>Your work, combat, career and relationships now build one permanent standing.</p></div><div><b>{Number(rank.score).toLocaleString()}</b><span>standing</span><Meter value={rank.score} max={rank.nextScore}/><small>{rank.nextName}{rank.nextScore>rank.score?` · ${rank.nextScore-rank.score} to go`:""}</small></div></section>
    <nav className="progress-tabs">{tabs.map(([key,label])=><button className={tab===key?"active":""} onClick={()=>setTab(key)} key={key}><GameIcon name={key==="story"?"missions":key==="factions"?"family":key==="combat"?"combat":"awards"} size={17}/>{label}</button>)}</nav>
    {error&&<div className="progress-alert bad">{error}<button onClick={()=>setError("")}>×</button></div>}
    {result&&<div className={`progress-result ${result.success===false?"miss":"good"}`}><GameIcon name={result.success===false?"history":"awards"}/><div><b>{result.mission||result.assignment||(result.success===false?"Assignment incomplete":"Record updated")}</b><span>{result.success===false?"The contact still paid for your time. ":""}{result.cash?`${money(result.cash)} · `:""}{result.xp?`${result.xp} XP · `:""}{result.reputation?`+${result.reputation} reputation`:""}{result.itemName?` · ${result.itemName}`:""}</span></div><button onClick={()=>setResult(null)}>×</button></div>}
    {tab==="story"&&<div className="story-chapters">{chapters.map(group=><section key={group.chapter}><header><span>{String(group.chapter).padStart(2,"0")}</span><div><small>BLACKWOOD CHAPTER</small><h3>{["","The Arrival","The Harbor Ledger","Clean Books","Made in Blackwood"][group.chapter]}</h3></div><em>{group.missions.filter(x=>x.claimedAt).length}/{group.missions.length}</em></header>{group.missions.map(mission=>{const ready=mission.unlocked&&!mission.claimedAt&&mission.progress>=mission.target;return <article className={`${mission.claimedAt?"claimed":""} ${!mission.unlocked?"locked":""}`} key={mission.id}><i>{mission.claimedAt?"✓":mission.sequence}</i><div><small>{mission.unlocked?`MISSION ${mission.sequence}`:"CLASSIFIED"}</small><b>{mission.title}</b><p>{mission.unlocked?mission.briefing:"Complete the previous mission to reveal this briefing."}</p>{mission.unlocked&&<><strong>{mission.objective}</strong><Meter value={mission.progress} max={mission.target}/><em>{mission.progress}/{mission.target}</em></>}</div><aside><b>{money(mission.cash)}</b><small>{mission.xp} XP · {mission.respect} respect</small>{mission.itemName&&<span>ITEM · {mission.itemName}</span>}<button disabled={busy||!ready} onClick={()=>act("bw_claim_story_mission",{p_mission_id:mission.id})}>{mission.claimedAt?"Completed":ready?"Claim chapter reward":mission.unlocked?"In progress":"Locked"}</button></aside></article>})}</section>)}</div>}
    {tab==="factions"&&<div className="faction-board"><header><div><small>REPEATABLE · NO ENERGY COST</small><h3>District assignments</h3><p>Keep playing whenever you want. The first {grind.fullEfficiencyRuns} daily runs pay full rewards; continued runs gradually settle at a {grind.minimumEfficiency}% floor and always grant progress.</p></div><span><b>{grind.today}</b><small>runs today</small></span></header>{data.careerCreditReady&&<button className="career-credit" disabled={busy} onClick={()=>act("bw_claim_career_influence")}>Convert your latest career shift into faction influence</button>}<div className="faction-grid">{data.factions.map(faction=><article key={faction.id}><header><i><GameIcon name={faction.id==="federal-trust"?"bank":faction.id==="northside-aid"?"hospital":faction.id==="harbor-union"?"work":"family"}/></i><div><small>{faction.district} · {faction.specialty}</small><b>{faction.name}</b></div><span>{faction.standing}</span></header><p>{faction.description}</p><div className="faction-rep"><b>{faction.reputation}</b><span>reputation</span><Meter value={faction.reputation} max={faction.nextReputation}/></div><div className="assignment-list">{(faction.assignments||[]).map(assignment=><section key={assignment.id}><div><small>LEVEL {assignment.level_required} · {assignment.base_chance}% BASE</small><b>{assignment.name}</b><p>{assignment.description}</p><em>{money(assignment.cash_reward)} · {assignment.xp_reward} XP · +{assignment.reputation_reward} rep</em></div><button disabled={busy||cooldown>0||data.player.level<assignment.level_required} onClick={()=>{setCooldown(grind.cooldownSeconds||20);act("bw_run_faction_assignment",{p_assignment_id:assignment.id,p_request_id:id()})}}>{data.player.level<assignment.level_required?`Level ${assignment.level_required}`:cooldown?`${cooldown}s`:"Take assignment"}</button></section>)}</div></article>)}</div></div>}
    {tab==="standing"&&<div className="standing-ledger"><header><small>HOW YOUR NAME IS BUILT</small><h3>Standing breakdown</h3><p>There is no paid shortcut. Every point comes from recorded play.</p></header><div>{Object.entries(data.breakdown||{}).map(([key,value])=><article key={key}><GameIcon name={key==="combat"?"combat":key==="career"?"work":key==="factions"?"family":key==="missions"?"missions":"awards"}/><span><small>{key}</small><b>{Number(value).toLocaleString()}</b></span></article>)}</div><section><b>Current title: {rank.name}</b><p>Next title: {rank.nextName}. Standing combines level, crime skill, respect, verified combat wins, story chapters, faction reputation and career tier.</p><Meter value={rank.score} max={rank.nextScore}/></section></div>}
    {tab==="combat"&&<div className="combat-mastery"><div className="mastery-seal"><GameIcon name="combat" size={42}/><small>COMBAT DISCIPLINE</small><b>{combat.mastery}</b><span>{combat.wins} wins · {combat.losses} losses</span></div><section><small>NEXT MASTERY</small><h3>{combat.nextWins>combat.wins?`${combat.nextWins-combat.wins} wins remaining`:"Maximum mastery reached"}</h3><Meter value={combat.wins} max={combat.nextWins}/><p>Combat mastery is earned only from server-resolved fights against authenticated players. Repeated-target protection prevents arranged farming.</p><dl><div><dt>Standing per win</dt><dd>25</dd></div><div><dt>Daily contracts</dt><dd>3</dd></div><div><dt>Same-target limit</dt><dd>3/hour</dd></div></dl></section></div>}
  </div>;
}
