import { useCallback, useEffect, useMemo, useState } from "react";
import { supabase } from "../online/supabase.js";
import GameIcon from "../ui/GameIcon.jsx";
import ReportButton from "../safety/ReportButton.jsx";
import "./family-command-center.css";

const TABS = [
  ["hq", "Headquarters", "family"], ["operations", "Operations", "missions"],
  ["war", "War room", "combat"], ["territory", "Territory", "city"],
  ["vault", "Vault & armory", "inventory"], ["chat", "Family chat", "chat"],
];
const money = value => `$${Number(value || 0).toLocaleString()}`;
const when = value => value ? new Date(value).toLocaleString([], { month: "short", day: "numeric", hour: "2-digit", minute: "2-digit" }) : "—";
const canManage = role => ["leader", "officer"].includes(role);

function Empty({ title, children }) { return <div className="family-empty"><GameIcon name="family" size={34}/><b>{title}</b><p>{children}</p></div>; }
function Stat({ label, value, detail }) { return <div className="family-stat"><small>{label}</small><b>{value}</b>{detail && <span>{detail}</span>}</div>; }
function Progress({ value, max }) { return <figure className="family-progress"><i style={{ width: `${Math.min(100, max ? value / max * 100 : 0)}%` }}/></figure>; }

export default function FamilyCommandCenter({ user }) {
  const [state, setState] = useState(null), [tab, setTab] = useState("hq"), [busy, setBusy] = useState(false), [notice, setNotice] = useState(""), [error, setError] = useState("");
  const [name, setName] = useState(""), [tag, setTag] = useState(""), [application, setApplication] = useState(""), [announcement, setAnnouncement] = useState("");
  const [amount, setAmount] = useState("1000"), [chat, setChat] = useState(""), [channel, setChannel] = useState("family"), [item, setItem] = useState("");
  const load = useCallback(async () => { const { data, error: problem } = await supabase.rpc("bw_family_snapshot"); if (problem) setError(problem.message); else { setState(data); setError(""); setAnnouncement(data?.family?.announcement || ""); } }, []);
  useEffect(() => { load(); const live = supabase.channel(`family-command-${user.id}`).on("postgres_changes", { event: "*", schema: "public", table: "bw_family_chat" }, load).on("postgres_changes", { event: "*", schema: "public", table: "bw_family_wars" }, load).on("postgres_changes", { event: "*", schema: "public", table: "bw_family_operations" }, load).subscribe(); return () => supabase.removeChannel(live); }, [load, user.id]);
  const action = async (rpc, params = {}, success = "Family record updated.") => { if (busy) return; setBusy(true); setError(""); const { data, error: problem } = await supabase.rpc(rpc, params); if (problem) setError(problem.message); else { setState(data); setNotice(success); setTimeout(() => setNotice(""), 2800); } setBusy(false); };
  const family = state?.family, role = state?.role, manager = canManage(role), operation = state?.operations?.[0], war = state?.war;
  const ownedIncome = useMemo(() => (state?.territories || []).filter(x => x.owned).reduce((sum, x) => sum + Number(x.income), 0), [state]);
  if (error && !state) return <div className="family-install"><b>Families 2.0 needs its database upgrade</b><p>Run <code>supabase/20260905_families_wars.sql</code> in the Supabase SQL Editor, then return here.</p><button onClick={load}>Try again</button><small>{error}</small></div>;
  if (!state) return <Empty title="Opening family records">Reading the live Blackwood family registry.</Empty>;
  if (!family) return <div className="family-recruit"><header><div><small>BLACKWOOD FAMILY REGISTRY</small><h2>Find your people</h2><p>Applications go to real family officers. Nobody is filled in by bots.</p></div><button onClick={load}>Refresh</button></header>{error && <div className="family-alert bad">{error}</div>}{notice && <div className="family-alert">{notice}</div>}<section className="family-found"><div><small>FOUND A NEW ORDER</small><b>Put your name on the city</b></div><input value={name} maxLength={24} placeholder="Family name" onChange={e => setName(e.target.value)}/><input value={tag} maxLength={5} placeholder="TAG" onChange={e => setTag(e.target.value.toUpperCase())}/><button disabled={busy || name.trim().length < 3 || tag.trim().length < 2} onClick={() => action("create_runner_crew", { p_name: name.trim(), p_tag: tag.trim(), p_color: "#9a5b35" }, "Your family has been founded.")}>Found family</button></section><div className="family-directory">{(state.directory || []).map((crew, index) => <article key={crew.id}><strong>{String(index + 1).padStart(2, "0")}</strong><i>{crew.tag}</i><div><small>{crew.division} division · {crew.rating} rating</small><b>{crew.name}</b><span>{crew.members}/24 members · {crew.territories} territories · {Number(crew.respect).toLocaleString()} respect</span></div><button disabled={busy} onClick={() => action("bw_family_apply", { p_crew_id: crew.id, p_message: application }, `Application sent to ${crew.name}.`)}>Apply</button></article>)}</div><label className="family-application-note"><span>Application note</span><textarea value={application} maxLength={240} placeholder="Tell the boss what you bring to the family…" onChange={e => setApplication(e.target.value)}/></label>{(state.applications || []).length > 0 && <section className="family-pending"><small>YOUR APPLICATIONS</small>{state.applications.map(x => <p key={x.id}><b>{x.crewName}</b><span className={x.status}>{x.status}</span></p>)}</section>}</div>;

  return <div className="family-command">
    <header className="family-hero"><div className="family-seal">{family.tag}</div><div><small>{family.division.toUpperCase()} DIVISION · {role.toUpperCase()}</small><h2>{family.name}</h2><p>{family.announcement}</p></div><div className="family-hero-rank"><b>#{(state.directory || []).findIndex(x => x.id === family.id) + 1}</b><span>City rank</span></div></header>
    <div className="family-scoreboard"><Stat label="RESPECT" value={Number(family.respect).toLocaleString()} detail={`Level ${family.level}`}/><Stat label="RATING" value={family.rating} detail={`${family.warsWon}W · ${family.warsLost}L`}/><Stat label="VAULT" value={money(family.vault)} detail="Shared funds"/><Stat label="CHAIN" value={family.chainCount || 0} detail={family.chainExpiresAt ? `Expires ${when(family.chainExpiresAt)}` : "Win external attacks"}/></div>
    <nav className="family-tabs">{TABS.map(([id, label, icon]) => <button className={tab === id ? "active" : ""} key={id} onClick={() => setTab(id)}><GameIcon name={icon}/><span>{label}</span></button>)}</nav>
    {error && <div className="family-alert bad">{error}</div>}{notice && <div className="family-alert">{notice}</div>}
    <main>
      {tab === "hq" && <div className="family-hq"><section className="family-paper"><header><div><small>THE FAMILY</small><h3>Authenticated roster</h3></div><span>{state.members.length}/24 seats filled</span></header><div className="family-roster">{state.members.map(member => <article key={member.userId}><i>{member.name.slice(0, 1).toUpperCase()}</i><div><b>{member.name}</b><small>{member.role} · joined {new Date(member.joinedAt).toLocaleDateString()}</small></div><span><b>{Number(member.contribution).toLocaleString()}</b><small>contribution</small></span>{role === "leader" && member.userId !== user.id && <select value={member.role} disabled={busy} onChange={e => action("bw_family_set_role", { p_user_id: member.userId, p_role: e.target.value }, `${member.name}'s role changed.`)}><option value="runner">Member</option><option value="officer">Officer</option></select>}</article>)}</div></section><aside><section><small>ORDERS FROM THE BOSS</small><textarea value={announcement} maxLength={240} disabled={!manager} onChange={e => setAnnouncement(e.target.value)}/>{manager && <button disabled={busy || !announcement.trim()} onClick={() => action("bw_family_announcement", { p_announcement: announcement }, "Headquarters order posted.")}>Post order</button>}</section><section><small>RECENT FAMILY BUSINESS</small>{state.logs.length === 0 ? <p>No family activity recorded yet.</p> : state.logs.slice(0, 8).map(log => <p key={log.id}><b>{log.summary}</b><span>{log.actor || "Family office"} · {when(log.createdAt)}</span></p>)}</section>{(state.applications || []).length > 0 && manager && <section className="family-applications"><small>APPLICATIONS</small>{state.applications.map(app => <p key={app.id}><b>{app.name}</b><em>{app.message || "No note supplied."}</em><span><button onClick={() => action("bw_family_decide_application", { p_application_id: app.id, p_accept: true }, "Applicant accepted.")}>Accept</button><button onClick={() => action("bw_family_decide_application", { p_application_id: app.id, p_accept: false }, "Application declined.")}>Decline</button></span></p>)}</section>}</aside></div>}
      {tab === "operations" && <div className="family-operations">{!operation ? <><header className="family-section-title"><div><small>ORGANIZED CRIME BOARD</small><h3>Choose the next score</h3><p>Every seat must be filled by a different authenticated family member.</p></div></header><div className="operation-grid">{state.templates.map(template => <article key={template.id}><small>{template.min_members} PEOPLE · {template.duration_minutes} MINUTES</small><h4>{template.name}</h4><p>{template.description}</p><div><b>{money(template.cash_reward)}</b><span>+{template.respect_reward} respect</span></div><ul>{template.roles.map(x => <li key={x}>{x}</li>)}</ul>{manager && <button disabled={busy} onClick={() => action("bw_family_create_operation", { p_template_id: template.id }, `${template.name} is recruiting.`)}>Set up operation</button>}</article>)}</div></> : <section className="active-operation"><header><div><small>{operation.status.toUpperCase()}</small><h3>{operation.name}</h3><p>{operation.description}</p></div><b>{money(operation.cashReward)}</b></header><Progress value={operation.slots.length} max={operation.minMembers}/><div className="operation-slots">{operation.roles.map(slotRole => { const seated = operation.slots.find(x => x.role === slotRole); return <article className={seated?.ready ? "ready" : ""} key={slotRole}><GameIcon name={seated ? "players" : "missions"}/><div><small>{slotRole}</small><b>{seated?.name || "Seat open"}</b></div>{!seated && operation.status === "recruiting" && <button disabled={busy} onClick={() => action("bw_family_join_operation", { p_operation_id: operation.id, p_role: slotRole }, `You took the ${slotRole} seat.`)}>Join</button>}{seated?.userId === user.id && operation.status === "recruiting" && <button onClick={() => action("bw_family_ready_operation", { p_operation_id: operation.id, p_ready: !seated.ready }, seated.ready ? "Marked not ready." : "You are ready.")}>{seated.ready ? "Ready ✓" : "Ready up"}</button>}</article>; })}</div>{operation.status === "recruiting" && manager && <button className="family-primary" disabled={busy || operation.slots.length < operation.minMembers || operation.slots.some(x => !x.ready)} onClick={() => action("bw_family_launch_operation", { p_operation_id: operation.id }, "The operation is underway.")}>Launch operation</button>}{operation.status === "running" && <div className="operation-running"><GameIcon name="work" size={30}/><b>Crew is on the job</b><span>Collection opens {when(operation.completes_at)}</span>{manager && <button disabled={busy || new Date(operation.completes_at) > new Date()} onClick={() => action("bw_family_collect_operation", { p_operation_id: operation.id }, "Operation paid out to every participant.")}>Collect payout</button>}</div>}</section>}</div>}
      {tab === "war" && <div className="family-war">{war ? <><header><div><small>RANKED FAMILY WAR</small><h3>{family.name} <em>vs</em> {war.opponent}</h3><p>Every winning attack against the opposing family scores one point.</p></div><span>Ends {when(war.endsAt)}</span></header><div className="war-score"><div><small>{family.tag}</small><b>{war.ourScore}</b></div><i>FIRST TO {war.target}</i><div><small>{war.opponent}</small><b>{war.theirScore}</b></div></div><Progress value={war.ourScore} max={war.target}/><section><small>LATEST HITS</small>{war.hits.length === 0 ? <Empty title="No hits landed">Open Attack and target a real member of the opposing family.</Empty> : war.hits.map((hit, i) => <p key={`${hit.createdAt}-${i}`}><b>{hit.attacker}</b> defeated {hit.defender}<span>{when(hit.createdAt)}</span></p>)}</section></> : <section className="war-enlist"><GameIcon name="combat" size={48}/><small>RANKED WAR OFFICE</small><h3>{family.queued ? "Matchmaking is active" : "Put the family name on the line"}</h3><p>{family.queued ? "The city will pair you with the closest queued rating. Only real families can be matched." : "A 72-hour race to 25 valid combat wins. Victory adds rating, $100,000 to the vault, and a permanent war win."}</p>{role === "leader" && <button disabled={busy || family.queued} onClick={() => action("bw_family_enlist_war", {}, "Family entered ranked matchmaking.")}>{family.queued ? "Waiting for a real opponent" : "Enlist for ranked war"}</button>}</section>}</div>}
      {tab === "territory" && <div className="family-territory"><header className="family-section-title"><div><small>BLACKWOOD CONTROL MAP</small><h3>Territory and collections</h3><p>Unclaimed districts can be bought from family funds. Existing ownership is never fabricated.</p></div><div><b>{money(ownedIncome)}</b><span>income per collection</span>{manager && <button disabled={busy || !ownedIncome} onClick={() => action("bw_family_collect_income", {}, "Territory income collected.")}>Collect income</button>}</div></header><div className="territory-grid">{state.territories.map(place => <article className={place.owned ? "ours" : place.ownerId ? "taken" : "open"} key={place.id}><span>{place.district}</span><h4>{place.name}</h4><p>{place.bonus}</p><dl><div><dt>Income</dt><dd>{money(place.income)}</dd></div><div><dt>Claim</dt><dd>{money(place.claim_cost)}</dd></div></dl><footer>{place.owned ? <b>Controlled by us</b> : place.ownerId ? <b>Held by {place.ownerName}</b> : manager ? <button disabled={busy || family.vault < place.claim_cost} onClick={() => action("bw_family_claim_territory", { p_territory_id: place.id }, `${place.name} is now under family control.`)}>Claim district</button> : <b>Unclaimed</b>}</footer></article>)}</div></div>}
      {tab === "vault" && <div className="family-vault"><section><header><div><small>SHARED TREASURY</small><h3>{money(family.vault)}</h3></div><GameIcon name="bank" size={34}/></header><p>Deposits come from your Exchange wallet. Only the boss and officers can withdraw.</p><div className="vault-transfer"><input type="number" min="1" value={amount} onChange={e => setAmount(e.target.value)}/><button disabled={busy || Number(amount) < 1} onClick={() => action("bw_family_vault_transfer", { p_direction: "deposit", p_amount: Number(amount) }, "Cash deposited.")}>Deposit</button>{manager && <button disabled={busy || Number(amount) < 1} onClick={() => action("bw_family_vault_transfer", { p_direction: "withdraw", p_amount: Number(amount) }, "Cash withdrawn.")}>Withdraw</button>}</div></section><section><header><div><small>YOUR UNEQUIPPED ITEMS</small><h3>Contribute equipment</h3></div><GameIcon name="inventory" size={34}/></header><select value={item} onChange={e => setItem(e.target.value)}><option value="">Choose an item</option>{state.inventory.filter(x => !x.equipped).map(x => <option value={x.itemId} key={x.itemId}>{x.name} · {x.quantity}</option>)}</select><button disabled={busy || !item} onClick={() => action("bw_family_armory_transfer", { p_direction: "deposit", p_item_id: item, p_quantity: 1 }, "Item added to the family armory.")}>Deposit one item</button></section><section className="armory-shelf"><header><div><small>FAMILY ARMORY</small><h3>Available equipment</h3></div></header>{state.armory.length === 0 ? <Empty title="The shelves are empty">Members can deposit unequipped inventory here.</Empty> : state.armory.map(x => <article key={x.itemId}><i><GameIcon name={x.kind === "weapon" ? "combat" : "inventory"}/></i><div><small>{x.rarity} · {x.quantity} available</small><b>{x.name}</b><span>{x.attack ? `+${x.attack} attack` : ""} {x.defense ? `+${x.defense} defense` : ""}</span></div>{manager && <button onClick={() => action("bw_family_armory_transfer", { p_direction: "withdraw", p_item_id: x.itemId, p_quantity: 1 }, `${x.name} withdrawn.`)}>Withdraw</button>}</article>)}</section></div>}
      {tab === "chat" && <div className="family-chat"><header><div><small>PRIVATE FAMILY COMMS</small><h3>{channel === "war" ? "War channel" : "Family channel"}</h3></div><select value={channel} onChange={e => setChannel(e.target.value)}><option value="family">Family</option><option value="war">War</option></select></header><div className="family-messages">{state.chat.filter(x => x.channel === channel).length === 0 ? <Empty title="The room is quiet">Send the first message to your authenticated family roster.</Empty> : state.chat.filter(x => x.channel === channel).map(message => <article className={message.userId === user.id ? "mine" : ""} key={message.id}><i>{message.name?.slice(0, 1) || "?"}</i><div><span><b>{message.name}</b><time>{when(message.createdAt)}</time></span><p>{message.body}</p>{message.userId!==user.id&&<ReportButton targetUser={message.userId} contentType="family_chat" contentId={message.id}/>}</div></article>)}</div><div className="family-compose"><input maxLength={500} value={chat} placeholder="Message the family…" onChange={e => setChat(e.target.value)} onKeyDown={e => { if (e.key === "Enter" && chat.trim()) { action("bw_family_send_chat", { p_channel: channel, p_body: chat.trim() }, "Message sent."); setChat(""); } }}/><button disabled={busy || !chat.trim()} onClick={() => { action("bw_family_send_chat", { p_channel: channel, p_body: chat.trim() }, "Message sent."); setChat(""); }}>Send</button></div></div>}
    </main>
    <footer className="family-leave"><span>Family actions use live authenticated accounts and server-owned outcomes.</span><button disabled={busy} onClick={() => action("leave_runner_crew", {}, "You left the family.")}>Leave family</button></footer>
  </div>;
}
