import { useCallback, useEffect, useState } from "react";
import { supabase } from "../online/supabase.js";
import "./economy.css";
const money=v=>`$${Number(v||0).toLocaleString()}`; const price=(v,d=5)=>Number(v||0).toFixed(d);
export default function EconomyHub({onWalletChange}){
 const [data,setData]=useState(null),[symbol,setSymbol]=useState("EUR/USD"),[side,setSide]=useState("buy"),[margin,setMargin]=useState(250),[leverage,setLeverage]=useState(3),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const load=useCallback(async(tick=false)=>{if(tick)await supabase.rpc("bw_fx_tick",{p_symbol:symbol});const {data:v,error:e}=await supabase.rpc("bw_fx_snapshot",{p_symbol:symbol});if(e)setError(e.message);else{setData(v);onWalletChange?.(v.balance)}},[symbol,onWalletChange]);
 useEffect(()=>{load(true);const id=setInterval(()=>load(true),5000);return()=>clearInterval(id)},[load]);
 const act=async(rpc,params)=>{setBusy(true);setError("");const {error:e}=await supabase.rpc(rpc,params);setBusy(false);if(e)setError(e.message);else load(true)};
 const q=data?.quote||{};return <div className="economy-page"><header><small>FEDERAL TRUST · CURRENCY DESK</small><h1>Economy</h1><p>Trade six continuously simulated currency markets. Performance builds a verified trader career.</p></header>{error&&<div className="economy-error">{error}</div>}<section className="trader-status"><div><small>TRADER RANK</small><b>{data?.profile?.rank||"Novice"}</b><em>{data?.profile?.closed_trades||0} closed trades · {money(data?.profile?.realized_pnl)} P&amp;L</em></div><div><small>BANK CAREER</small><b>{data?.profile?.bank_offer_unlocked?"Offer available":"Building record"}</b><em>{data?.profile?.next_rank_hint||"Close profitable, disciplined trades to advance."}</em></div><div><small>AVAILABLE CASH</small><b>{money(data?.balance)}</b></div></section><div className="fx-layout"><aside>{(data?.pairs||[]).map(p=><button className={symbol===p.symbol?"active":""} onClick={()=>setSymbol(p.symbol)} key={p.symbol}><span><b>{p.symbol}</b><small>{p.name}</small></span><em>{price(p.mid,p.digits)}</em></button>)}</aside><section className="fx-terminal"><header><div><small>LIVE QUOTE</small><h2>{symbol}</h2></div><div><span>SELL <b>{price(q.bid,q.digits)}</b></span><span>BUY <b>{price(q.ask,q.digits)}</b></span></div></header><div className="fx-chart">{(data?.candles||[]).slice(-32).map((c,i)=>{const all=data.candles;const lo=Math.min(...all.map(x=>Number(x.low))),hi=Math.max(...all.map(x=>Number(x.high)));return <i key={i} style={{height:`${15+(Number(c.close)-lo)/Math.max(.00001,hi-lo)*80}%`}}/>})}</div><div className="order-ticket"><div><button className={side==="buy"?"active":""} onClick={()=>setSide("buy")}>BUY</button><button className={side==="sell"?"active sell":""} onClick={()=>setSide("sell")}>SELL</button></div><label>Margin<input type="number" min="100" step="50" value={margin} onChange={e=>setMargin(Number(e.target.value))}/></label><label>Leverage<select value={leverage} onChange={e=>setLeverage(Number(e.target.value))}>{[1,3,5,10].map(x=><option key={x} value={x}>{x}×</option>)}</select></label><button disabled={busy} onClick={()=>act("bw_fx_open",{p_symbol:symbol,p_side:side,p_margin:margin,p_leverage:leverage,p_request_id:crypto.randomUUID()})}>Open position</button></div><div className="positions"><h3>Open positions</h3>{!data?.positions?.length?<p>No exposure. Choose a pair and open a measured position.</p>:data.positions.map(p=><article key={p.id}><div><b>{p.symbol} · {p.side.toUpperCase()}</b><small>{p.leverage}× · {money(p.margin)} margin</small></div><span><small>ENTRY / CURRENT</small><b>{price(p.entry_price)} / {price(p.current_price)}</b></span><em className={p.unrealized_pnl>=0?"up":"down"}>{money(p.unrealized_pnl)}</em><button disabled={busy} onClick={()=>act("bw_fx_close",{p_position_id:p.id,p_request_id:crypto.randomUUID()})}>Close</button></article>)}</div></section></div></div>
}
