import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { supabase } from "../online/supabase.js";
import TradingChart from "./TradingChart.jsx";
import "./economy.css";
import "./white-terminal.css";

const LOTS = [0.01,0.05,0.10,0.50,1,2,5];
const money = value => `$${Number(value || 0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const price = (value,digits=5) => Number(value || 0).toFixed(digits);
const age = value => { if(!value)return "No provider update"; const seconds=Math.max(0,Math.floor((Date.now()-new Date(value).getTime())/1000)); return seconds<60?`${seconds}s ago`:seconds<3600?`${Math.floor(seconds/60)}m ago`:`${Math.floor(seconds/3600)}h ago`; };

export default function EconomyHub({ onWalletChange }) {
  const [data,setData]=useState(null),[symbol,setSymbol]=useState("XAU/USD"),[timeframe,setTimeframe]=useState("1min"),[side,setSide]=useState("buy"),[lots,setLots]=useState(.01),[stopLoss,setStopLoss]=useState(""),[takeProfit,setTakeProfit]=useState("");
  const [openLeverage,setOpenLeverage]=useState(500),[deposit,setDeposit]=useState(1000),[transfer,setTransfer]=useState(1000),[busy,setBusy]=useState(false),[error,setError]=useState(""),[feedNote,setFeedNote]=useState("Connecting to live market…");
  const positionsRef=useRef([]);
  useEffect(()=>{positionsRef.current=data?.positions||[]},[data?.positions]);
  const snapshot=useCallback(async()=>{const{data:value,error:problem}=await supabase.rpc("bw_broker_snapshot",{p_symbol:symbol,p_timeframe:timeframe});if(problem){setError(problem.message);return null}setData(value);onWalletChange?.(value.walletBalance);return value},[symbol,timeframe,onWalletChange]);
  const refresh=useCallback(async(showBusy=false)=>{if(showBusy)setBusy(true);setError("");const{data:feed,error:feedError}=await supabase.functions.invoke("market-feed",{body:{symbol,timeframe}});if(feedError)setFeedNote(feedError.message);else if(feed?.error)setFeedNote(feed.error);else setFeedNote(feed?.refreshed?`Live candles updated · ${feed.candles} bars`:`Live cache · ${age(feed?.cachedAt)}`);await snapshot();if(showBusy)setBusy(false)},[symbol,timeframe,snapshot]);
  useEffect(()=>{refresh(true);const timer=setInterval(()=>refresh(false),60000);return()=>clearInterval(timer)},[refresh]);
  const refreshLivePnl=useCallback(async()=>{const symbols=[...new Set(positionsRef.current.map(position=>position.symbol))].slice(0,8);if(!symbols.length)return;const{data:feed,error:feedError}=await supabase.functions.invoke("market-feed",{body:{mode:"quotes",symbols}});if(feedError)setFeedNote(`Live P/L delayed · ${feedError.message}`);else if(feed?.error)setFeedNote(`Live P/L delayed · ${feed.error}`);else setFeedNote(feed?.refreshed?`Live P/L updated · ${feed.refreshed} market${feed.refreshed===1?"":"s"}`:"Live P/L quote cache");await snapshot()},[snapshot]);
  const hasOpenPositions=Boolean(data?.positions?.length);
  useEffect(()=>{if(!hasOpenPositions)return;let stopped=false,timer;const tick=async()=>{await refreshLivePnl();if(stopped)return;const count=Math.max(1,new Set(positionsRef.current.map(position=>position.symbol)).size);const delay=Math.max(15000,Math.ceil(count/8*60000));timer=setTimeout(tick,delay)};tick();return()=>{stopped=true;clearTimeout(timer)}},[hasOpenPositions,refreshLivePnl]);
  const action=async(rpc,params,success)=>{setBusy(true);setError("");const{data:value,error:problem}=await supabase.rpc(rpc,params);if(problem)setError(problem.message);else{setData(value);onWalletChange?.(value.walletBalance);if(success)setFeedNote(success)}setBusy(false)};
  const account=data?.account,quote=data?.quote||{},digits=quote.digits||5;
  const estimate=useMemo(()=>{if(!account||!quote.ask)return{notional:0,margin:0};const contract=Number(quote.contractSize||100000),notional=quote.assetClass==="metal"?contract*lots*Number(quote.ask):contract*lots;return{notional,margin:Math.ceil(notional/account.leverage)}},[account,quote,lots]);
  if(data&&!account)return <div className="broker-onboarding"><section><small>FEDERAL TRUST · PRIME BROKERAGE</small><h1>Open a trading account</h1><p>Your brokerage balance is separate from cash on hand. Choose the leverage profile, transfer an opening deposit, then trade real provider-backed markets using lots.</p><div className="account-choice"><label><span>Account leverage</span><select value={openLeverage} onChange={e=>setOpenLeverage(Number(e.target.value))}><option value="500">1:500</option><option value="1000">1:1000</option></select><em>Higher leverage lowers margin but increases liquidation risk.</em></label><label><span>Opening deposit</span><input type="number" min="1000" step="500" value={deposit} onChange={e=>setDeposit(Number(e.target.value))}/><em>{money(data.walletBalance)} available on hand.</em></label></div>{error&&<div className="economy-error">{error}</div>}<button disabled={busy||deposit<1000||deposit>data.walletBalance} onClick={()=>action("bw_broker_open_account",{p_leverage:openLeverage,p_deposit:deposit},"Trading account opened.")}>{busy?"Opening account…":"Open live-market account"}</button><footer>Virtual in-game funds only. This is not a real brokerage account and cannot hold or withdraw real money.</footer></section></div>;
  return <div className="economy-page live-terminal">
    <header className="broker-title"><div><small>FEDERAL TRUST · LIVE MARKET DESK</small><h1>Prime FX</h1><p>Provider-backed Forex and metals. No simulated candles.</p></div><div className={`feed-state ${quote.source==="twelve_data"?"live":"stale"}`}><i/><span><b>{quote.source==="twelve_data"?"LIVE FEED":"FEED NOT READY"}</b><small>{age(quote.updated_at)} · {feedNote}</small></span><button disabled={busy} onClick={()=>refresh(true)}>↻</button></div></header>
    {error&&<div className="economy-error">{error}</div>}
    <section className="broker-metrics"><div><small>BALANCE</small><b>{money(account?.balance)}</b></div><div><small>EQUITY</small><b>{money(account?.equity)}</b></div><div><small>USED MARGIN</small><b>{money(account?.usedMargin)}</b></div><div><small>FREE MARGIN</small><b>{money(account?.freeMargin)}</b></div><div className={Number(account?.floatingPnl)>=0?"positive":"negative"}><small>FLOATING P/L</small><b>{money(account?.floatingPnl)}</b></div><div><small>MARGIN LEVEL</small><b>{account?.marginLevel==null?"—":`${account.marginLevel}%`}</b></div></section>
    <div className="broker-workspace"><aside className="market-watch"><header><b>Market Watch</b><span>{data?.pairs?.length||0} symbols</span></header>{(data?.pairs||[]).map(market=><button className={symbol===market.symbol?"active":""} onClick={()=>setSymbol(market.symbol)} key={market.symbol}><i className={Number(market.mid)>=Number(market.base_price)?"up":"down"}/><span><b>{market.symbol.replace("/","")}</b><small>{market.asset_class}</small></span><em><b>{price(market.bid,market.digits)}</b><small>{price(market.ask,market.digits)}</small></em></button>)}</aside>
      <main className="dealing-area"><header className="instrument-bar"><div><small>{quote.assetClass?.toUpperCase()} · {symbol.replace("/","")}</small><h2>{quote.name||symbol}</h2></div><div className="top-quote sell"><small>SELL</small><b>{price(quote.bid,digits)}</b></div><div className="top-quote buy"><small>BUY</small><b>{price(quote.ask,digits)}</b></div><div className="spread"><small>SPREAD</small><b>{quote.ask?((Number(quote.ask)-Number(quote.bid))*Math.pow(10,digits)).toFixed(1):"—"}</b></div></header>
        <TradingChart candles={data?.candles||[]} digits={digits} symbol={symbol.replace("/","")} timeframe={timeframe} onTimeframe={setTimeframe} quote={quote}/>
        <section className="trade-panel"><div className="deal-switch"><button className={side==="sell"?"active sell":""} onClick={()=>setSide("sell")}><small>SELL MARKET</small><b>{price(quote.bid,digits)}</b></button><button className={side==="buy"?"active buy":""} onClick={()=>setSide("buy")}><small>BUY MARKET</small><b>{price(quote.ask,digits)}</b></button></div><label><span>Volume</span><select value={lots} onChange={e=>setLots(Number(e.target.value))}>{LOTS.map(value=><option value={value} key={value}>{value.toFixed(2)} lot{value===1?"":"s"}</option>)}</select></label><label><span>Stop loss</span><input type="number" step={Math.pow(10,-digits)} placeholder="Optional" value={stopLoss} onChange={e=>setStopLoss(e.target.value)}/></label><label><span>Take profit</span><input type="number" step={Math.pow(10,-digits)} placeholder="Optional" value={takeProfit} onChange={e=>setTakeProfit(e.target.value)}/></label><div className="order-estimate"><span>Notional <b>{money(estimate.notional)}</b></span><span>Required margin <b>{money(estimate.margin)}</b></span><span>Leverage <b>1:{account?.leverage}</b></span></div><button className={`execute ${side}`} disabled={busy||quote.source!=="twelve_data"} onClick={()=>action("bw_broker_open_position",{p_symbol:symbol,p_side:side,p_lots:lots,p_stop_loss:stopLoss?Number(stopLoss):null,p_take_profit:takeProfit?Number(takeProfit):null,p_request_id:crypto.randomUUID()},`${side.toUpperCase()} order filled.`)}>{busy?"Sending order…":`${side.toUpperCase()} ${lots.toFixed(2)} LOT`}</button></section>
      </main>
      <aside className="account-drawer"><header><small>TRADING ACCOUNT</small><b>{account?.account_number}</b><span>{data?.profile?.rank||"Novice"} trader</span></header><section><label><span>Leverage</span><select value={account?.leverage||500} disabled={busy||data?.positions?.length>0} onChange={e=>action("bw_broker_set_leverage",{p_leverage:Number(e.target.value)},"Account leverage changed.")}><option value="500">1:500</option><option value="1000">1:1000</option></select></label>{data?.positions?.length>0&&<small>Close positions to change leverage.</small>}</section><section><label><span>Cash transfer</span><input type="number" min="1" step="100" value={transfer} onChange={e=>setTransfer(Number(e.target.value))}/></label><div><button disabled={busy} onClick={()=>action("bw_broker_transfer",{p_direction:"deposit",p_amount:transfer},"Funds deposited.")}>Deposit</button><button disabled={busy} onClick={()=>action("bw_broker_transfer",{p_direction:"withdraw",p_amount:transfer},"Funds withdrawn.")}>Withdraw</button></div><small>{money(data?.walletBalance)} cash on hand</small></section><section className="risk-card"><small>STOP-OUT</small><b>50% margin level</b><p>Positions are liquidated automatically when account equity falls to half of used margin.</p></section><section><small>CAREER RECORD</small><dl><div><dt>Closed trades</dt><dd>{data?.profile?.closed_trades||0}</dd></div><div><dt>Winning trades</dt><dd>{data?.profile?.winning_trades||0}</dd></div><div><dt>Realized P/L</dt><dd>{money(data?.profile?.realized_pnl)}</dd></div></dl></section></aside>
    </div>
    <section className="position-terminal"><header><div><b>Positions</b><span>{data?.positions?.length||0} open{data?.positions?.length?" · LIVE P/L":""}</span></div><div><button className="active">OPEN POSITIONS</button><button>ORDER HISTORY</button></div></header>{!data?.positions?.length?<div className="no-positions"><b>No open exposure</b><span>Select a market, lot size and direction to place an order.</span></div>:<div className="position-table"><div className="position-row headings"><span>SYMBOL</span><span>DIRECTION</span><span>VOLUME</span><span>ENTRY</span><span>CURRENT</span><span>MARGIN</span><span>SL / TP</span><span>NET P/L</span><span/></div>{data.positions.map(position=><div className="position-row" key={position.id}><span><b>{position.symbol.replace("/","")}</b></span><span className={position.side}>{position.side.toUpperCase()}</span><span>{Number(position.lots||0).toFixed(2)} lots</span><span>{price(position.entry_price,position.symbol.includes("JPY")?3:position.symbol.includes("XAU")?2:5)}</span><span>{price(position.currentPrice,position.symbol.includes("JPY")?3:position.symbol.includes("XAU")?2:5)}</span><span>{money(position.margin)}</span><span>{position.stop_loss||"—"} / {position.take_profit||"—"}</span><span className={Number(position.unrealizedPnl)>=0?"profit":"loss"}>{money(position.unrealizedPnl)}</span><button disabled={busy} onClick={()=>action("bw_broker_close_position",{p_position_id:position.id,p_request_id:crypto.randomUUID()},"Position closed.")}>Close</button></div>)}</div>}</section>
    <footer className="broker-disclaimer">In-game virtual trading only · market data may be delayed or unavailable outside provider coverage · no real money, investment service or trade execution</footer>
  </div>;
}
