import {useMemo,useState} from "react";
import {LOOT,ItemArt,RARITIES} from "../online/Inventory.jsx";
import {CHIP_DROP_TIERS,LIFE_SKILLS,MATERIAL_LABELS,RECIPES,canCraft,formatRemaining,normalizeEconomyState} from "./economyRules.js";
import "./economy-hub.css";

const itemById=(id)=>LOOT.find((item)=>item.id===id);
export default function EconomyHub({open,initialTab="auction",state,inventory,balance=0,busy,onClose,onRefresh,onStartSkill,onClaimSkill,onCraft,onList,onBuy,onCancel}){
 const [tab,setTab]=useState(initialTab),[query,setQuery]=useState(""),[discipline,setDiscipline]=useState("all"),[notice,setNotice]=useState("");
 const [sellItem,setSellItem]=useState(""),[sellPrice,setSellPrice]=useState(1000);
 const economy=normalizeEconomyState(state); const now=Date.now();
 const owned=useMemo(()=>new Set(inventory?.owned||[]),[inventory?.owned]);
 const listings=economy.listings.filter((entry)=>{const item=itemById(entry.itemId);return item?.name.toLowerCase().includes(query.toLowerCase())});
 const recipes=RECIPES.filter((recipe)=>discipline==="all"||recipe.discipline===discipline);
 const run=async(work,success)=>{setNotice("");try{await work?.();setNotice(success);await onRefresh?.();}catch(error){setNotice(error.message||"Economy action failed")}};
 if(!open)return null;
 return <div className="econ-overlay" role="dialog" aria-modal="true" aria-label="Neo Economy"><main className="econ-hub">
  <header className="econ-head"><div className="econ-mark"><i>環</i><span/></div><div><small>NEO GRID // PLAYER ECONOMY</small><h1>Commerce & Fabrication</h1><p>Gather, build and trade account-owned equipment.</p></div><aside><small>AVAILABLE</small><b>¥{Number(balance).toLocaleString()}</b></aside><button onClick={onClose} aria-label="Close economy">×</button></header>
  <nav>{[["auction","Auction","市"],["crafting","Crafting","造"],["lifeskills","Life Skills","技"]].map(([id,label,glyph])=><button key={id} className={tab===id?"active":""} onClick={()=>setTab(id)}><i>{glyph}</i><span>{label}</span></button>)}</nav>
  {notice&&<button className="econ-notice" onClick={()=>setNotice("")}>{notice}<b>×</b></button>}
  {!economy.authority&&<section className="econ-setup"><i>雲</i><h2>Economy migration required</h2><p>Run the latest Neo Economy SQL migration in Supabase to activate secure player trading and crafting.</p></section>}
  {economy.authority&&tab==="auction"&&<section className="auction-deck"><header><div><small>LIVE PLAYER LISTINGS</small><h2>Auction House</h2></div><input value={query} placeholder="Search item or set" onChange={e=>setQuery(e.target.value)}/></header><div className="auction-grid">{listings.map(entry=>{const item=itemById(entry.itemId);return item&&<article key={entry.id} style={{"--tier":RARITIES[item.rarity].color}}><ItemArt item={item} level={entry.enhancement}/><div><small>{item.setName} · +{entry.enhancement||0}</small><h3>{item.name}</h3><span>Seller {entry.sellerName||"Runner"}</span></div><footer><b>¥{Number(entry.price).toLocaleString()}</b><button disabled={busy||owned.has(item.id)} onClick={()=>run(()=>onBuy(entry.id),"Purchase secured")}>{owned.has(item.id)?"Already owned":"Buy"}</button></footer></article>})}{!listings.length&&<p className="econ-empty">No matching active listings.</p>}</div><aside className="auction-sell"><h3>List Unequipped Gear</h3><select value={sellItem} onChange={e=>setSellItem(e.target.value)}><option value="">Choose an item</option>{(inventory?.owned||[]).filter(id=>!Object.values(inventory?.equipped||{}).includes(id)).map(id=>{const item=itemById(id);return item&&<option key={id} value={id}>{item.name} +{inventory?.enhancement?.[id]||0}</option>})}</select><label>Price<input type="number" min="100" max="100000000" value={sellPrice} onChange={e=>setSellPrice(e.target.value)}/></label><button disabled={busy||!sellItem||Number(sellPrice)<100} onClick={()=>run(async()=>{await onList(sellItem,Number(sellPrice));setSellItem("")},"Item placed in secure escrow")}>List for 24 hours</button><small>1% listing deposit · 5% fee only when sold</small></aside><aside className="my-listings"><h3>My Listings</h3>{economy.myListings.map(entry=><button key={entry.id} onClick={()=>run(()=>onCancel(entry.id),"Listing returned to inventory")}>{itemById(entry.itemId)?.name||entry.itemId}<b>Cancel</b></button>)}</aside></section>}
  {economy.authority&&tab==="crafting"&&<section className="craft-deck"><header><div><small>80 SERVER RECIPES</small><h2>Fabrication Bay</h2><p>The old Workshop is now one account-owned crafting system.</p></div><select value={discipline} onChange={e=>setDiscipline(e.target.value)}><option value="all">All disciplines</option>{[...new Set(RECIPES.map(r=>r.discipline))].map(id=><option key={id} value={id}>{RECIPES.find(r=>r.discipline===id).label}</option>)}</select></header><div className="craft-grid">{recipes.map(recipe=>{const item=itemById(recipe.itemId);const ready=canCraft(recipe,economy.materials);return <article key={recipe.id} className={ready?"ready":""}><div className="craft-machine"><i/><em/><span>{item?<ItemArt item={item}/>:"造"}</span></div><div><small>LV {recipe.level} · {recipe.label}</small><h3>{recipe.name}</h3><p>{Object.entries(recipe.cost).map(([id,n])=><span className={Number(economy.materials[id]||0)>=n?"have":"need"} key={id}>{MATERIAL_LABELS[id]||id} {economy.materials[id]||0}/{n}</span>)}</p></div><button disabled={busy||!ready} onClick={()=>run(()=>onCraft(recipe.id),`${recipe.name} completed`)}>{ready?"Craft":"Materials needed"}</button></article>})}</div></section>}
  {economy.authority&&tab==="lifeskills"&&<section className="life-deck"><header><div><small>ACCOUNT PROFESSIONS</small><h2>Life Skills</h2><p>Gather materials actively or send one server-timed work order.</p></div><div className="chip-odds">{CHIP_DROP_TIERS.map(t=><span key={t.id}><b>{t.name}</b>{t.odds}</span>)}</div></header><div className="life-grid">{LIFE_SKILLS.map(skill=>{const data=economy.skills[skill.id]||{level:1,xp:0};const job=economy.jobs.find(j=>j.skill===skill.id);return <article key={skill.id} style={{"--skill":skill.color}}><i>{skill.glyph}</i><div><small>LEVEL {data.level}</small><h3>{skill.name}</h3><p>{skill.detail}</p><em>{skill.materials.map(id=>MATERIAL_LABELS[id]).join(" · ")}</em></div>{job?<button className={new Date(job.completesAt).getTime()<=now?"claim":"working"} disabled={busy||new Date(job.completesAt).getTime()>now} onClick={()=>run(()=>onClaimSkill(job.id),`${skill.name} materials claimed`)}>{formatRemaining(job.completesAt,now)}</button>:<button disabled={busy} onClick={()=>run(()=>onStartSkill(skill.id),`${skill.name} work order started`)}>Begin work</button>}</article>})}</div><div className="material-vault"><h3>Material Vault</h3>{Object.entries(MATERIAL_LABELS).map(([id,label])=><span key={id}><b>{label}</b>{Number(economy.materials[id]||0).toLocaleString()}</span>)}</div></section>}
 </main></div>;
}
