import { useCallback, useEffect, useRef, useState } from "react";
import { supabase } from "./supabase.js";
import FamilyCommandCenter from "../families/FamilyCommandCenter.jsx";
import "./community-hub.css";
import "./players.css";

const TABS = [["chat", "World Chat", "●"], ["players", "Players", "◉"], ["rankings", "Rankings", "♛"], ["families", "Families", "◆"]];

function Empty({ title, text }) { return <div className="community-empty"><i>◇</i><b>{title}</b><p>{text}</p></div>; }

export default function CommunityHub({ user, initialTab = "chat" }) {
  const [tab, setTab] = useState(initialTab), [messages, setMessages] = useState([]), [players, setPlayers] = useState([]), [rankings, setRankings] = useState([]), [text, setText] = useState(""), [busy, setBusy] = useState(false), [status, setStatus] = useState("Connecting to Blackwood…");
  const end = useRef(null);
  useEffect(() => setTab(initialTab), [initialTab]);
  const loadChat = useCallback(async () => { const { data, error } = await supabase.from("chat_messages").select("id,body,created_at,user_id,profiles(display_name,avatar_url)").is("deleted_at", null).order("created_at", { ascending: false }).limit(80); if (error) setStatus(error.message); else { setMessages((data || []).reverse()); setStatus("World channel · live"); } }, []);
  const loadPlayers = useCallback(async () => { const { data, error } = await supabase.from("profiles").select("id,display_name,avatar_url,last_seen_at,created_at").order("last_seen_at", { ascending: false }).limit(100); if (error) setStatus(error.message); else setPlayers(data || []); }, []);
  const loadRankings = useCallback(async () => { await supabase.rpc("sync_my_leaderboard"); const { data, error } = await supabase.from("leaderboard_entries").select("user_id,display_name,level,money,wins,title,evolution,updated_at").order("level", { ascending: false }).order("money", { ascending: false }).limit(100); if (error) setStatus(error.message); else setRankings(data || []); }, []);
  useEffect(() => { loadChat(); loadPlayers(); loadRankings(); const heartbeat = () => supabase.from("profiles").update({ last_seen_at: new Date().toISOString() }).eq("id", user.id); heartbeat(); const heartbeatId = setInterval(heartbeat, 60000); const channel = supabase.channel("blackwood-community").on("postgres_changes", { event: "*", schema: "public", table: "chat_messages" }, loadChat).on("postgres_changes", { event: "*", schema: "public", table: "leaderboard_entries" }, loadRankings).subscribe(state => { if (state === "SUBSCRIBED") setStatus("Online · live updates"); }); return () => { clearInterval(heartbeatId); supabase.removeChannel(channel); }; }, [user.id, loadChat, loadPlayers, loadRankings]);
  useEffect(() => { if (tab === "chat") end.current?.scrollIntoView({ block: "end" }); }, [messages, tab]);
  const send = async () => { const body = text.trim(); if (!body || busy) return; setBusy(true); setText(""); const { error } = await supabase.from("chat_messages").insert({ user_id: user.id, body }); if (error) { setText(body); setStatus(error.message); } setBusy(false); };
  return <><div className="page-head community-title"><div><small>REAL PLAYERS · LIVE DATA</small><h1>Blackwood Network</h1><p>No bots, no placeholder users. Everything here comes from authenticated accounts.</p></div><span className="live-status"><i />{status}</span></div><section className="community"><nav>{TABS.map(([id, label, icon]) => <button className={tab === id ? "active" : ""} onClick={() => setTab(id)} key={id}><i>{icon}</i>{label}</button>)}</nav>
    {tab === "chat" && <div className="chat-view"><header><div><small>PUBLIC CHANNEL</small><b>World Chat</b></div><span>{messages.length} recent messages</span></header><div className="messages">{messages.length === 0 && <Empty title="The channel is quiet" text="Be the first authenticated player to say something." />}{messages.map(message => <article className={message.user_id === user.id ? "mine" : ""} key={message.id}><i>{(message.profiles?.display_name || "?").slice(0, 1).toUpperCase()}</i><div><span><b>{message.profiles?.display_name || "Player"}</b><time>{new Date(message.created_at).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}</time></span><p>{message.body}</p></div></article>)}<div ref={end} /></div><div className="compose"><input value={text} maxLength={240} placeholder="Message the city…" onChange={e => setText(e.target.value)} onKeyDown={e => e.key === "Enter" && send()} /><span>{text.length}/240</span><button disabled={!text.trim() || busy} onClick={send}>Send</button></div></div>}
    {tab === "players" && <div className="players-view"><header><div><small>AUTHENTICATED ACCOUNTS</small><b>Player Directory</b></div><button onClick={loadPlayers}>Refresh</button></header>{players.length === 0 ? <Empty title="No players found" text="Only real Google-authenticated accounts are listed here." /> : <div className="player-list">{players.map(player => { const online = Date.now() - new Date(player.last_seen_at).getTime() < 180000; return <article className={player.id === user.id ? "mine" : ""} key={player.id}><i>{(player.display_name || "?").slice(0, 1).toUpperCase()}</i><div><b>{player.display_name}</b><small>{player.id === user.id ? "You" : `Joined ${new Date(player.created_at).toLocaleDateString()}`}</small></div><span className={online ? "online" : ""}><i />{online ? "Online" : `Seen ${new Date(player.last_seen_at).toLocaleDateString()}`}</span></article>; })}</div>}</div>}
    {tab === "rankings" && <div className="ranking-view"><header><div><small>HALL OF FAME</small><b>City Rankings</b></div><button onClick={loadRankings}>Refresh</button></header>{rankings.length === 0 ? <Empty title="No ranked players yet" text="Rankings appear after authenticated players save progress." /> : <div className="ranking-list">{rankings.map((entry, index) => <article className={entry.user_id === user.id ? "mine" : ""} key={entry.user_id}><strong>{index + 1}</strong><i>{entry.display_name.slice(0, 1).toUpperCase()}</i><div><b>{entry.display_name}</b><small>{entry.title || "Associate"}</small></div><span><b>LV {entry.level}</b><small>${Number(entry.money || 0).toLocaleString()}</small></span><em>{Number(entry.wins || 0)} wins</em></article>)}</div>}</div>}
    {tab === "families" && <FamilyCommandCenter user={user} />}
  </section></>;
}
