import { useEffect, useMemo, useState } from "react";
import { supabase } from "../online/supabase.js";
import GameIcon from "../ui/GameIcon.jsx";
import "./district-operations.css";

const money=value=>`$${Number(value||0).toLocaleString()}`;
const APPROACHES={careful:["Quiet plan","Recon, timing and dexterity"],direct:["Direct action","Strength, defence and control"],social:["Inside contact","Crime skill and intelligence"]};
const STAGES=["Intel","Preparation","Execution","Extraction"];

export default function DistrictOperations({onState}) {
  const [data,setData]=useState(null),[districtId,setDistrictId]=useState(null),[operationId,setOperationId]=useState(null),[approach,setApproach]=useState("careful"),[mode,setMode]=useState("solo"),[busy,setBusy]=useState(false),[error,setError]=useState(""),[event,setEvent]=useState(null);
  const load=async()=>{setError("");const{data:value,error:problem}=await supabase.rpc("bw_operations_snapshot");if(problem)setError(problem.message);else{setData(value);setDistrictId(current=>current||value?.districts?.[0]?.id);}};
  useEffect(()=>{load()},[]);
  const district=useMemo(()=>data?.districts?.find(item=>item.id===districtId)||data?.districts?.[0],[data,districtId]);
  const operation=useMemo(()=>district?.operations?.find(item=>item.id===operationId)||district?.operations?.[0],[district,operationId]);
  const invoke=async(rpc,params)=>{if(busy)return;setBusy(true);setError("");setEvent(null);const{data:value,error:problem}=await supabase.rpc(rpc,params);if(problem)setError(problem.message);else{setData(value.operations||value);setEvent(value.event||null);onState?.(value.state?.player||value.operations?.player);}setBusy(false)};
  const begin=()=>invoke("bw_begin_district_operation",{p_operation_id:operation.id,p_approach:approach,p_mode:mode});
  const advance=choice=>invoke("bw_advance_district_operation",{p_choice:choice,p_request_id:crypto.randomUUID()});
  if(!data)return <div className="operations-page"><header className="operations-hero"><small>BLACKWOOD FIELD OFFICE</small><h1>District Operations</h1><p>{error||"Opening the city operations board…"}</p>{error&&<button onClick={load}>Retry</button>}</header></div>;
  const active=data.active;
  return <div className="operations-page">
    <header className="operations-hero"><div><small>BLACKWOOD FIELD OFFICE · LIVE</small><h1>District Operations</h1><p>Multi-stage PvE work against clearly marked NPC crews. No energy cost—heat and efficiency keep the streets fair.</p></div><aside><span><small>TODAY</small><b>{data.grind?.today||0} runs</b></span><span><small>EFFICIENCY</small><b>{Math.round((data.grind?.nextEfficiency||1)*100)}%</b></span><span><small>FLOOR</small><b>40%</b></span></aside></header>
    {error&&<div className="operations-alert bad">{error}<button onClick={()=>setError("")}>×</button></div>}
    {event&&<div className={`operations-alert ${event.success?"good":"warn"}`}><b>{event.title}</b><span>{event.message}</span>{event.completed&&<em>{money(event.cash)} · {event.xp} XP · {event.mastery} mastery{event.itemName?` · Found ${event.itemName}`:""}</em>}</div>}
    {active?<ActiveOperation active={active} busy={busy} onAdvance={advance}/>:<>
      <section className="district-board"><header><span><small>TACTICAL MAP</small><h2>Choose a district</h2></span><em>Heat falls by 5 every hour</em></header><div>{data.districts.map(item=><button className={district?.id===item.id?"active":""} style={{"--district":item.accent}} onClick={()=>{setDistrictId(item.id);setOperationId(null)}} key={item.id}><i><GameIcon name="operations"/></i><span><small>{item.zone}</small><b>{item.name}</b><em>Threat {item.threat} · {item.clears} clears</em></span><strong>{item.heat}<small>HEAT</small></strong><figure><i style={{width:`${item.heat}%`}}/></figure></button>)}</div></section>
      {district&&<section className="operation-dossier" style={{"--district":district.accent}}><header><div><small>{district.zone} · THREAT {district.threat}</small><h2>{district.name}</h2><p>{district.summary}</p></div><dl><div><dt>Heat</dt><dd>{district.heat}/100</dd></div><div><dt>Mastery</dt><dd>{district.mastery}</dd></div><div><dt>Clears</dt><dd>{district.clears}</dd></div></dl></header><div className="operation-list">{district.operations.map(item=><button className={operation?.id===item.id?"active":""} disabled={data.player.level<item.requiredLevel} onClick={()=>setOperationId(item.id)} key={item.id}><span><small>DIFFICULTY {item.difficulty}</small><b>{item.name}</b><em>{item.briefing}</em></span><aside><small>NPC CAPTAIN</small><b>{item.captainName}</b><em>{money(item.baseCash)} · {item.baseXp} XP</em></aside>{data.player.level<item.requiredLevel&&<strong>LEVEL {item.requiredLevel}</strong>}</button>)}</div>
      {operation&&<div className="operation-plan"><div><small>CHOOSE APPROACH</small><nav>{Object.entries(APPROACHES).map(([id,[name,detail]])=><button className={approach===id?"active":""} onClick={()=>setApproach(id)} key={id}><GameIcon name={id==="direct"?"combat":id==="social"?"social":"targets"}/><span><b>{name}</b><em>{detail}</em></span></button>)}</nav></div><div><small>TEAM</small><nav>{[["solo","Solo","Your account stats only"],["family","Family-supported","Real family members add support"]].map(([id,name,detail])=><button className={mode===id?"active":""} onClick={()=>setMode(id)} key={id}><GameIcon name={id==="solo"?"players":"family"}/><span><b>{name}</b><em>{detail}</em></span></button>)}</nav></div><button className="begin-operation" disabled={busy||data.player.level<operation.requiredLevel} onClick={begin}>{busy?"Preparing dossier…":"Begin operation"}<span>No energy required</span></button><p className="operation-odds"><b>Rare find:</b> {(Number(operation.rareChance)*100).toFixed(1)}% on a successful extraction. Repeated runs always grant progress, with rewards never falling below 40%.</p></div>}</section>}
    </>}
  </div>;
}

function ActiveOperation({active,busy,onAdvance}) {
  return <section className="active-operation" style={{"--district":active.accent}}><header><div><small>{active.districtName} · ACTIVE DOSSIER</small><h2>{active.operationName}</h2><p>{active.briefing}</p></div><span><small>CONDITION</small><b>{active.condition}%</b><figure><i style={{width:`${active.condition}%`}}/></figure></span></header><div className="stage-track">{STAGES.map((stage,index)=><div className={index+1<active.currentStage?"done":index+1===active.currentStage?"current":""} key={stage}><i>{index+1<active.currentStage?"✓":index+1}</i><span><small>STAGE {index+1}</small><b>{stage}</b></span></div>)}</div><article><small>CURRENT OBJECTIVE</small><h3>{active.stageTitle}</h3><p>{active.stageBrief}</p>{active.currentStage===3&&<div className="npc-card"><GameIcon name="combat"/><span><small>NPC CAPTAIN</small><b>{active.captainName}</b><em>Difficulty {active.difficulty}</em></span></div>}<div className="active-metrics"><span><small>APPROACH</small><b>{APPROACHES[active.approach]?.[0]}</b></span><span><small>TEAM</small><b>{active.mode==="family"?`${active.supporters} family members`:"Solo"}</b></span><span><small>RECORD</small><b>{active.successes} passed · {active.failures} setbacks</b></span></div></article><footer><small>Choose how to handle this stage</small><div>{Object.entries(APPROACHES).map(([id,[name,detail]])=><button disabled={busy} onClick={()=>onAdvance(id)} key={id}><GameIcon name={id==="direct"?"combat":id==="social"?"social":"targets"}/><span><b>{name}</b><em>{detail}</em></span></button>)}</div></footer></section>;
}
