import { useEffect, useMemo, useState } from "react";
import { supabase } from "../online/supabase.js";
import GameIcon from "../ui/GameIcon.jsx";

const money=value=>`$${Number(value||0).toLocaleString()}`;
const age=value=>{const seconds=Math.max(0,Math.floor((Date.now()-new Date(value).getTime())/1000));return seconds<60?`${seconds}s ago`:seconds<3600?`${Math.floor(seconds/60)}m ago`:`${Math.floor(seconds/3600)}h ago`};
const icon=kind=>kind==="weapon"?"combat":kind==="armor"?"property":kind==="accessory"?"awards":"inventory";

export default function MarketHub({onState}) {
  const [data,setData]=useState(null),[tab,setTab]=useState("browse"),[busy,setBusy]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState(""),[query,setQuery]=useState(""),[rarity,setRarity]=useState("all"),[quantities,setQuantities]=useState({});
  const [itemId,setItemId]=useState(""),[sellQuantity,setSellQuantity]=useState(1),[unitPrice,setUnitPrice]=useState(100);
  const accept=value=>{const market=value?.market||value;setData(market);if(value?.state?.player)onState?.(value.state.player)};
  const load=async()=>{const{data:value,error:problem}=await supabase.rpc("bw_market_snapshot");if(problem)setError(problem.message);else{setError("");accept(value)}};
  useEffect(()=>{load();const timer=setInterval(load,15000);return()=>clearInterval(timer)},[]);
  useEffect(()=>{const item=data?.sellable?.find(entry=>entry.itemId===itemId);if(item)setUnitPrice(item.basePrice)},[itemId,data?.sellable]);
  const act=async(rpc,params,message)=>{if(busy)return;setBusy(true);setError("");setNotice("");const{data:value,error:problem}=await supabase.rpc(rpc,params);if(problem)setError(problem.message);else{accept(value);setNotice(message)}setBusy(false)};
  const listings=useMemo(()=>(data?.listings||[]).filter(item=>(rarity==="all"||item.rarity===rarity)&&`${item.name} ${item.sellerName}`.toLowerCase().includes(query.toLowerCase())),[data?.listings,query,rarity]);
  const selected=data?.sellable?.find(item=>item.itemId===itemId);
  if(!data)return <div className="market-loading">Opening the Blackwood Exchange…</div>;
  return <div className="blackwood-market">{error&&<div className="market-alert bad">{error}</div>}{notice&&<div className="market-alert good">{notice}</div>}
    <header className="market-ledger"><div><small>PLAYER-OWNED COMMERCE</small><h2>Blackwood Exchange</h2><p>Real listings, secured inventory escrow and a permanent sale ledger.</p></div><span><small>ON HAND</small><b>{money(data.walletBalance)}</b><em>5% seller commission</em></span></header>
    <nav className="market-tabs">{[["browse","Market floor"],["sell","Sell items"],["mine","My listings"],["history","Price book"]].map(([id,label])=><button className={tab===id?"active":""} onClick={()=>setTab(id)} key={id}>{label}</button>)}</nav>
    {tab==="browse"&&<section className="market-floor"><header><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search item or seller"/><select value={rarity} onChange={event=>setRarity(event.target.value)}><option value="all">All rarities</option>{["common","uncommon","rare","epic","legendary"].map(value=><option value={value} key={value}>{value}</option>)}</select><button onClick={load}>Refresh</button></header>{listings.length===0?<Empty title="No matching listings" text="Only inventory placed by real players appears here."/>:<div className="market-listings">{listings.map(listing=>{const quantity=Math.min(listing.remaining,Math.max(1,quantities[listing.id]||1));return <article className={listing.rarity} key={listing.id}><i><GameIcon name={icon(listing.kind)}/></i><div><small>{listing.rarity} · {listing.slot||listing.kind}</small><b>{listing.name}</b><p>Sold by {listing.sellerName} · {listing.remaining} available</p><em>Listed {age(listing.createdAt)}</em></div><span><b>{money(listing.unitPrice)}</b><small>each</small><input aria-label={`Quantity of ${listing.name}`} type="number" min="1" max={listing.remaining} value={quantity} onChange={event=>setQuantities(current=>({...current,[listing.id]:Number(event.target.value)}))}/><button disabled={busy||listing.mine||data.walletBalance<listing.unitPrice*quantity} onClick={()=>act("bw_market_buy",{p_listing_id:listing.id,p_quantity:quantity,p_request_id:crypto.randomUUID()},`Bought ${quantity} × ${listing.name}.`)}>{listing.mine?"Your listing":`Buy · ${money(listing.unitPrice*quantity)}`}</button></span></article>})}</div>}</section>}
    {tab==="sell"&&<section className="market-sell"><div><small>ESCROW LISTING</small><h3>Put inventory on the market</h3><p>Listed items leave your usable inventory immediately and return when you cancel. Equipped copies cannot be sold.</p></div>{data.sellable.length===0?<Empty title="Nothing available to sell" text="Unequip an item or obtain loot before opening a listing."/>:<form onSubmit={event=>{event.preventDefault();act("bw_market_list",{p_item_id:itemId,p_quantity:sellQuantity,p_unit_price:unitPrice},`${selected?.name||"Item"} listed.`)}}><label><span>ITEM</span><select required value={itemId} onChange={event=>setItemId(event.target.value)}><option value="">Choose inventory</option>{data.sellable.map(item=><option value={item.itemId} key={item.itemId}>{item.name} · {item.available} available</option>)}</select></label><label><span>QUANTITY</span><input type="number" min="1" max={selected?.available||1} value={sellQuantity} onChange={event=>setSellQuantity(Number(event.target.value))}/></label><label><span>PRICE EACH</span><input type="number" min="1" value={unitPrice} onChange={event=>setUnitPrice(Number(event.target.value))}/></label><aside><small>ESTIMATED PROCEEDS</small><b>{money(sellQuantity*unitPrice*.95)}</b><em>after 5% commission</em></aside><button disabled={busy||!selected||sellQuantity>selected.available}>Open listing</button></form>}</section>}
    {tab==="mine"&&<section className="market-mine">{data.mine.length===0?<Empty title="No listing history" text="Your active, sold and cancelled listings will be recorded here."/>:data.mine.map(listing=><article key={listing.id}><i className={listing.status}/><div><small>{listing.rarity}</small><b>{listing.name}</b><span>{listing.remaining}/{listing.quantity} remaining · {money(listing.unitPrice)} each</span></div><em>{listing.status}</em>{listing.status==="active"&&<button disabled={busy} onClick={()=>act("bw_market_cancel",{p_listing_id:listing.id},`${listing.name} returned to inventory.`)}>Cancel & return</button>}</article>)}</section>}
    {tab==="history"&&<section className="price-book">{data.history.length===0?<Empty title="The ledger is blank" text="Price history appears after real players complete market sales."/>:<><header><span>ITEM</span><span>30D VOLUME</span><span>LOW / HIGH</span><span>AVERAGE</span></header>{data.history.map(item=><article key={item.itemId}><span><i className={item.rarity}/><b>{item.name}</b></span><span>{item.volume}</span><span>{money(item.low)} / {money(item.high)}</span><strong>{money(item.average)}</strong></article>)}</>}</section>}
  </div>;
}

function Empty({title,text}){return <div className="market-empty"><i>◇</i><b>{title}</b><p>{text}</p></div>}
