import { useCallback, useEffect, useState } from "react";
import { CricketGameV2, NeonReflex, CircuitMemory } from "./arcade/ArcadeGames.jsx";
import TradingTerminal from "./trading/TradingTerminal.jsx";

const SAVE_KEY = "blackwood-city-save-v1";
const clamp = (v, min, max) => Math.max(min, Math.min(max, v));
const money = (v) => `$${Math.floor(v).toLocaleString()}`;
const xpNeed = (level) => 100 + level * 65;

export const INITIAL = {
  name: "Vincent Moretti", title: "Street Soldier", level: 7, xp: 238, cash: 54820, bank: 125000,
  energy: 92, nerve: 31, health: 850, happy: 420, maxEnergy: 100, maxNerve: 40, maxHealth: 1000, maxHappy: 500,
  strength: 118.4, defense: 93.2, speed: 76.8, dexterity: 81.5, crimeSkill: 14, respect: 186, merits: 3,
  job: "Dock Bookkeeper", jobPoints: 44, jailUntil: 0, inventory: ["Brass Knuckles", "Tailored Vest", "First Aid Kit", "Bottle of Bourbon"],
  log: [
    { text: "The Marconi family collected $12,400 from the waterfront.", tone: "good" },
    { text: "Your protection expires in 2 days.", tone: "warn" },
    { text: "Don Salvatore left new orders at the social club.", tone: "plain" },
  ],
};

const NAV = [["home", "Overview", "◆"], ["crimes", "Crimes", "♠"], ["gym", "Gym", "▲"], ["work", "Work", "▣"], ["city", "City", "●"], ["family", "Family", "♛"], ["inventory", "Inventory", "▤"], ["arcade", "Arcade", "♣"]];
const CRIMES = [
  { name: "Lift from a corner store", type: "Petty Crime", nerve: 2, chance: 92, reward: [70, 160], xp: 6, skill: 0, time: "A few minutes" },
  { name: "Run a numbers slip", type: "Fraud", nerve: 4, chance: 82, reward: [280, 640], xp: 14, skill: 4, time: "Half an hour" },
  { name: "Steal a parked sedan", type: "Auto Theft", nerve: 7, chance: 69, reward: [900, 2100], xp: 25, skill: 9, time: "One hour" },
  { name: "Hijack a cargo truck", type: "Organized Crime", nerve: 11, chance: 54, reward: [2800, 6500], xp: 45, skill: 16, time: "Three hours" },
  { name: "Crack the Bellini vault", type: "Grand Larceny", nerve: 16, chance: 38, reward: [8000, 18000], xp: 80, skill: 24, time: "All night" },
];
const STATS = [["strength", "Strength", "Hit harder in fights", "STR"], ["defense", "Defense", "Take less damage", "DEF"], ["speed", "Speed", "Act before your rival", "SPD"], ["dexterity", "Dexterity", "Improve accuracy and evasion", "DEX"]];
const PLACES = [
  ["market", "The Exchange", "TRADING FLOOR", "Trade the gold market through the family's private desk.", "$"],
  ["arcade", "Rossi's Arcade", "GAMES & WAGERS", "Cricket, reflex and memory games behind the old pool hall.", "♣"],
  ["hospital", "St. Mercy Hospital", "MEDICAL", "Recover health and see who has been admitted.", "+"],
  ["bank", "Federal Trust", "FINANCE", "Keep clean money safe and review your holdings.", "▥"],
  ["dealer", "Southside Arms", "EQUIPMENT", "Weapons, armor and supplies. Cash only.", "†"],
  ["estate", "Moretti Estate", "PROPERTY", "Your home raises happiness and protects your holdings.", "⌂"],
];

function loadGame() { try { return { ...INITIAL, ...JSON.parse(localStorage.getItem(SAVE_KEY) || "{}") }; } catch { return INITIAL; } }
function Resource({ label, value, max, tone, icon }) { return <div className={`resource ${tone}`}><div><span><i>{icon}</i>{label}</span><b>{Math.floor(value)} <em>/ {max}</em></b></div><figure><i style={{ width: `${clamp(value / max * 100, 0, 100)}%` }} /></figure></div>; }
function Panel({ title, eyebrow, action, children, className = "" }) { return <section className={`panel ${className}`}><header><div>{eyebrow && <small>{eyebrow}</small>}<h2>{title}</h2></div>{action}</header>{children}</section>; }
function PageHead({ eyebrow, title, text, children }) { return <div className="page-head"><div><small>{eyebrow}</small><h1>{title}</h1>{text && <p>{text}</p>}</div>{children}</div>; }

function Overview({ p, go }) {
  const goals = [["Earn $75,000 in cash", p.cash, 75000], ["Raise crime skill to 20", p.crimeSkill, 20], ["Train any stat above 125", Math.max(p.strength, p.defense, p.speed, p.dexterity), 125]];
  return <><PageHead eyebrow="SUNDAY, AUGUST 30 · BLACKWOOD CITY" title={<>Good evening, <em>Vincent.</em></>} text="The city remembers who shows up. Make today count."><button className="primary" onClick={() => go("crimes")}>Find work <b>→</b></button></PageHead>
    <div className="overview-grid"><Panel title="City business" eyebrow="WHAT NEEDS ATTENTION"><button className="feature-order" onClick={() => go("family")}><i>M</i><span><small>NEW FAMILY ORDER</small><b>The Harbor Collection</b><em>Don Salvatore wants the docks secured before midnight.</em></span><strong>›</strong></button><div className="quick-grid">{[["crimes", "♠", "Crimes", `${p.nerve} nerve ready`], ["gym", "▲", "Train", `${p.energy} energy ready`], ["work", "▣", "Work", "Shift available"], ["city", "●", "City", "12 locations open"]].map(x => <button key={x[0]} onClick={() => go(x[0])}><i>{x[1]}</i><span><b>{x[2]}</b><small>{x[3]}</small></span><em>›</em></button>)}</div></Panel>
      <Panel title="Your standing" eyebrow="THIS WEEK" className="standing"><div className="rank"><span><b>#1,842</b><small>CITY RANK</small></span></div><dl>{[["Family respect", p.respect], ["Net worth", money(p.cash + p.bank)], ["Crimes completed", 47], ["Merit points", p.merits]].map(x => <div key={x[0]}><dt>{x[0]}</dt><dd>{x[1]}</dd></div>)}</dl></Panel></div>
    <div className="lower-grid"><Panel title="Long game" eyebrow="CURRENT GOALS"><div className="goals">{goals.map(([label, value, max]) => <div key={label}><span><b>{label}</b><em>{Math.min(value, max).toFixed(0)} / {max}</em></span><figure><i style={{ width: `${clamp(value / max * 100, 0, 100)}%` }} /></figure></div>)}</div></Panel><Panel title="Word on the street" eyebrow="RECENT ACTIVITY"><div className="feed">{p.log.slice(0, 3).map((x, i) => <div className={x.tone} key={i}><i /><p>{x.text}<small>{i ? `${i} hour${i > 1 ? "s" : ""} ago` : "8 minutes ago"}</small></p></div>)}</div></Panel></div></>;
}

function Crimes({ p, act }) { return <><PageHead eyebrow="BUILD YOUR REPUTATION" title="Crimes" text="Start small. Learn the streets. Never talk to the police."><div className="score"><small>CRIME SKILL</small><b>{p.crimeSkill}</b></div></PageHead><Panel title="Available jobs" eyebrow={`${p.nerve} NERVE AVAILABLE`}><div className="crime-list">{CRIMES.map((c, n) => { const locked = p.crimeSkill < c.skill; const chance = clamp(c.chance + (p.crimeSkill - c.skill) * 1.2, 12, 96); return <article className={locked ? "locked" : ""} key={c.name}><i>0{n + 1}</i><div><small>{c.type}</small><b>{c.name}</b><em>{c.time}</em></div><div className="odds"><small>SUCCESS</small><b>{Math.round(chance)}%</b><figure><i style={{ width: `${chance}%` }} /></figure></div><div className="take"><small>TAKE</small><b>{money(c.reward[0])}–{money(c.reward[1])}</b><em>{c.nerve} nerve</em></div><button disabled={locked || p.nerve < c.nerve} onClick={() => act(c)}>{locked ? `Skill ${c.skill}` : "Do job"}</button></article>; })}</div></Panel></>; }
function Gym({ p, train }) { return <><PageHead eyebrow="NORTHSIDE ATHLETIC CLUB" title="The Gym" text="Discipline wins fights before they begin."><div className="score"><small>ENERGY</small><b>{p.energy}/{p.maxEnergy}</b></div></PageHead><div className="gym-grid">{STATS.map(([key, name, desc, code]) => <Panel title={name} eyebrow={code} key={key} className="stat-card"><strong>{p[key].toFixed(1)}</strong><p>{desc}</p><div><span><small>COST</small><b>5 energy</b></span><button disabled={p.energy < 5} onClick={() => train(key)}>Train × 1</button></div></Panel>)}</div><aside className="coach"><b>“</b><p><strong>Coach Lombardi says:</strong><br />Numbers don't matter in here. The next repetition does.</p></aside></>; }
function Work({ p, work }) { return <><PageHead eyebrow="EARN CLEAN MONEY" title="Employment" text="A respectable position is the best alibi money can buy." /><div className="split"><Panel title={p.job} eyebrow="CURRENT POSITION" className="job"><i>B&amp;S</i><h3>Blackwood & Sons Shipping</h3><p>Balance manifests, smooth over discrepancies, and make sure the right crates leave the docks.</p><dl><div><dt>Daily pay</dt><dd>$1,850</dd></div><div><dt>Job points</dt><dd>{p.jobPoints}</dd></div><div><dt>Required energy</dt><dd>10</dd></div></dl><button className="primary full" disabled={p.energy < 10} onClick={work}>Complete shift</button></Panel><Panel title="Career ladder" eyebrow="SHIPPING COMPANY"><div className="ladder">{[["Dock Hand", "Complete"], ["Bookkeeper", "Current"], ["Freight Manager", "80 points"], ["Port Director", "200 points"]].map(([name, note], i) => <div className={i < 2 ? "done" : ""} key={name}><i>{i < 2 ? "✓" : i + 1}</i><span><b>{name}</b><small>{note}</small></span></div>)}</div></Panel></div></>; }
function City({ go, market }) { return <><PageHead eyebrow="BLACKWOOD DIRECTORY" title="The City" text="Every block has an opportunity, if you know which door to knock on." /><div className="city-grid">{PLACES.map(([id, name, kicker, desc, icon]) => <button key={id} onClick={() => id === "market" ? market() : id === "arcade" ? go("arcade") : null}><i>{icon}</i><span><small>{kicker}</small><b>{name}</b><em>{desc}</em></span><strong>›</strong></button>)}</div></>; }
function Family({ p }) { const people = [["Don Salvatore", "Boss", "ONLINE"], ["Elena Rossi", "Underboss", "12m"], ["Frankie Vale", "Caporegime", "1h"], ["Tommy Greco", "Soldier", "3h"]]; return <><PageHead eyebrow="THE MARCONI FAMILY" title="Family business" text="Loyalty is worth more than blood. Respect is worth more than money."><div className="score"><small>YOUR RESPECT</small><b>{p.respect}</b></div></PageHead><div className="split"><Panel title="The Harbor Collection" eyebrow="ACTIVE ORDER" className="order"><div className="order-art">M</div><p>Three dock foremen are behind on this week's envelope. Remind them who keeps the waterfront peaceful.</p><span><b>1 of 3</b> collections made</span><figure><i /></figure><button className="primary full">Continue order</button></Panel><Panel title="Made members" eyebrow="YOUR INNER CIRCLE"><div className="members">{people.map(([name, rank, seen], i) => <div key={name}><i>{name.split(" ").map(x => x[0]).join("")}</i><p><b>{name}</b><small>{rank}</small></p><em className={i ? "" : "online"}>{seen}</em></div>)}</div><button className="secondary full">Open family hall</button></Panel></div></>; }
function Inventory({ p, useItem }) { return <><PageHead eyebrow="PERSONAL EFFECTS" title="Inventory" text="What you carry says something about how you do business." /><Panel title="Your possessions" eyebrow={`${p.inventory.length} ITEMS`}><div className="inventory">{p.inventory.map((item, i) => <article key={`${item}${i}`}><div>{["✦", "V", "+", "B"][i] || "•"}</div><small>{i < 2 ? "EQUIPMENT" : "CONSUMABLE"}</small><b>{item}</b><p>{["+12 strength damage", "+18 defense", "Restores 250 health", "Restores 20 happiness"][i] || "Personal item"}</p><button onClick={() => useItem(item, i)}>{i < 2 ? "Equipped" : "Use item"}</button></article>)}</div></Panel></>; }

function Arcade({ p, finish }) {
  const [game, setGame] = useState(null); const [bet, setBet] = useState(250); const done = result => { finish(result.reward ?? Math.floor(bet * (result.mult || 0))); setGame(null); };
  if (game) return <><PageHead eyebrow="ROSSI'S BACK ROOM" title={game === "cricket" ? "Street Cricket" : game === "reflex" ? "Quick Hands" : "The Memory Table"}><button className="secondary" onClick={() => setGame(null)}>Leave table</button></PageHead><div className="arcade-stage">{game === "cricket" ? <CricketGameV2 bet={bet} onEnd={done} /> : game === "reflex" ? <NeonReflex onFinish={done} /> : <CircuitMemory onFinish={done} />}</div></>;
  return <><PageHead eyebrow="GAMES OF SKILL & CHANCE" title="Rossi's Arcade" text="Upstairs is for families. The serious games are behind the green door." /><div className="bet"><span><small>YOUR STAKE</small><b>{money(bet)}</b></span><input type="range" min="50" max={Math.min(2500, p.cash)} step="50" value={bet} onChange={e => setBet(Number(e.target.value))} /><em>Wallet: {money(p.cash)}</em></div><div className="arcade-menu">{[["cricket", "Street Cricket", "Twelve balls. Three wickets. Read the pitch and swing."], ["reflex", "Quick Hands", "Twenty signals. The window gets shorter every round."], ["memory", "The Memory Table", "Watch the sequence. Repeat it clean. Eight rounds to win."]].map(([id, name, desc], i) => <button key={id} onClick={() => setGame(id)}><i>0{i + 1}</i><span><small>ROSSI'S HOUSE GAME</small><b>{name}</b><p>{desc}</p><em>Sit down →</em></span></button>)}</div></>;
}

export default function MafiaGame({ initialPlayer = null, character = null, user = null, onPlayerChange = null, onSignOut = null }) {
  const [p, setP] = useState(() => initialPlayer || loadGame()), [page, setPage] = useState("home"), [notice, setNotice] = useState(null), [market, setMarket] = useState(false), [menu, setMenu] = useState(false), [accountOpen, setAccountOpen] = useState(false);
  useEffect(() => { localStorage.setItem(SAVE_KEY, JSON.stringify(p)); onPlayerChange?.(p); }, [p, onPlayerChange]);
  useEffect(() => { const id = setInterval(() => setP(x => ({ ...x, energy: clamp(x.energy + 1, 0, x.maxEnergy), nerve: clamp(x.nerve + 1, 0, x.maxNerve), health: clamp(x.health + 5, 0, x.maxHealth) })), 60000); return () => clearInterval(id); }, []);
  const flash = (text, tone = "good") => { setNotice({ text, tone }); setTimeout(() => setNotice(null), 3200); };
  const addXp = (state, amount) => { const x = { ...state, xp: state.xp + amount }; if (x.xp >= xpNeed(x.level)) { x.xp -= xpNeed(x.level); x.level++; x.maxHealth += 50; x.health = x.maxHealth; flash(`Level ${x.level} reached. The city is taking notice.`); } return x; };
  const crime = c => { if (p.nerve < c.nerve || p.jailUntil > Date.now()) return; const success = Math.random() * 100 < clamp(c.chance + (p.crimeSkill - c.skill) * 1.2, 12, 96); setP(x => { let y = { ...x, nerve: x.nerve - c.nerve }; if (success) { const take = Math.floor(c.reward[0] + Math.random() * (c.reward[1] - c.reward[0])); y.cash += take; y.crimeSkill += Math.random() < .4 ? 1 : 0; y.respect += Math.ceil(c.nerve / 3); y.log = [{ text: `${c.name} paid ${money(take)}.`, tone: "good" }, ...y.log]; flash(`Clean work. You took ${money(take)}.`); } else { y.jailUntil = Date.now() + 30000; y.log = [{ text: `The ${c.type.toLowerCase()} job went bad.`, tone: "warn" }, ...y.log]; flash("The job went bad. You're cooling off for 30 seconds.", "bad"); } return addXp(y, success ? c.xp : 2); }); };
  const train = key => setP(x => { if (x.energy < 5) return x; const gain = 1.8 + x.happy / x.maxHappy * 2.2; flash(`${key[0].toUpperCase() + key.slice(1)} increased by ${gain.toFixed(1)}.`); return { ...x, energy: x.energy - 5, happy: clamp(x.happy - 4, 0, x.maxHappy), [key]: x[key] + gain }; });
  const work = () => setP(x => { if (x.energy < 10) return x; flash("Shift complete. $1,850 added to your wallet."); return addXp({ ...x, energy: x.energy - 10, cash: x.cash + 1850, jobPoints: x.jobPoints + 5, log: [{ text: "Completed a clean shift at Blackwood & Sons.", tone: "good" }, ...x.log] }, 10); });
  const useItem = (item, index) => { if (index < 2) return; setP(x => ({ ...x, health: item === "First Aid Kit" ? clamp(x.health + 250, 0, x.maxHealth) : x.health, happy: item !== "First Aid Kit" ? clamp(x.happy + 20, 0, x.maxHappy) : x.happy, inventory: x.inventory.filter((_, i) => i !== index) })); flash(`${item} used.`); };
  const finish = reward => setP(x => { flash(reward ? `The house pays you ${money(reward)}.` : "The house keeps the stake.", reward ? "good" : "bad"); return { ...x, cash: x.cash + reward }; });
  const syncWallet = useCallback(cash => setP(x => ({ ...x, cash })), []);
  const content = { home: <Overview p={p} go={setPage} />, crimes: <Crimes p={p} act={crime} />, gym: <Gym p={p} train={train} />, work: <Work p={p} work={work} />, city: <City go={setPage} market={() => setMarket(true)} />, family: <Family p={p} />, inventory: <Inventory p={p} useItem={useItem} />, arcade: <Arcade p={p} finish={finish} /> }[page];
  const initials = (character?.codename || p.name).split(/\s+/).map(x => x[0]).join("").slice(0, 2).toUpperCase();
  return <div className="game-shell"><header className="topbar"><button className="hamb" onClick={() => setMenu(!menu)}>☰</button><button className="brand" onClick={() => setPage("home")}><i>M</i><span><b>MORETTI</b><small>BLACKWOOD CITY</small></span></button><div className="resources"><Resource label="Energy" value={p.energy} max={p.maxEnergy} tone="energy" icon="⚡" /><Resource label="Nerve" value={p.nerve} max={p.maxNerve} tone="nerve" icon="♦" /><Resource label="Health" value={p.health} max={p.maxHealth} tone="health" icon="+" /><Resource label="Happy" value={p.happy} max={p.maxHappy} tone="happy" icon="♥" /></div><button className="cash"><small>ON HAND</small><b>{money(p.cash)}</b></button><button className="avatar" onClick={() => setAccountOpen(!accountOpen)} aria-label="Account menu">{initials}</button>{accountOpen && <div className="account-menu"><small>SIGNED IN</small><b>{character?.codename || p.name}</b><em>{user?.email}</em><button onClick={onSignOut}>Sign out</button></div>}</header>
    <aside className={`sidebar ${menu ? "open" : ""}`}><div className="profile"><i>VM<span>{p.level}</span></i><div><b>{p.name}</b><small>{p.title}</small><figure><i style={{ width: `${p.xp / xpNeed(p.level) * 100}%` }} /></figure><em>{p.xp} / {xpNeed(p.level)} XP</em></div></div><nav>{NAV.map(([id, label, icon]) => <button className={page === id ? "active" : ""} key={id} onClick={() => { setPage(id); setMenu(false); }}><i>{icon}</i>{label}{id === "family" && <span>1</span>}</button>)}</nav><button className="market-link" onClick={() => setMarket(true)}><i>$</i><span><b>The Exchange</b><small>Trading floor open</small></span><em>›</em></button><blockquote>“Keep your friends close. Keep your ledger closer.”<small>— Don Salvatore</small></blockquote></aside>
    <main>{content}</main>{notice && <div className={`toast ${notice.tone}`}><i>{notice.tone === "bad" ? "!" : "✓"}</i>{notice.text}</div>}<TradingTerminal open={market} balance={p.cash} onClose={() => setMarket(false)} onWalletChange={syncWallet} /></div>;
}
