import { useEffect, useState } from "react";
import { supabase } from "../online/supabase.js";
import "./casino.css";
const money = v => `$${Number(v || 0).toLocaleString()}`;
const Card = ({ card }) => <i className={/[HD]/.test(card) ? "red" : ""}>{card?.replace("H","♥").replace("D","♦").replace("C","♣").replace("S","♠")}</i>;
export default function CasinoHub({ onWalletChange }) {
  const [tab,setTab]=useState("blackjack"),[bet,setBet]=useState(100),[state,setState]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState("");
  const call=async(rpc,params={})=>{setBusy(true);setError("");const {data,error:e}=await supabase.rpc(rpc,params);setBusy(false);if(e){setError(e.message);return null}setState(data);if(data?.balance!=null)onWalletChange?.(data.balance);return data};
  useEffect(()=>{call("bw_casino_snapshot")},[]);
  const play=()=>tab==="slots"?call("bw_slots_spin",{p_bet:bet,p_request_id:crypto.randomUUID()}):tab==="roulette"?call("bw_roulette_spin",{p_bet:bet,p_bet_type:"red",p_number:null,p_request_id:crypto.randomUUID()}):call("bw_blackjack_start",{p_bet:bet,p_request_id:crypto.randomUUID()});
  const game=state?.blackjack;
  return <div className="casino-page"><header><small>ROSSI'S SOCIAL CLUB</small><h1>Casino</h1><p>Every hand, reel and wheel is settled by the city server.</p></header>{error&&<div className="casino-error">{error}</div>}<nav>{[["blackjack","Blackjack"],["slots","Slots"],["roulette","Roulette"]].map(x=><button className={tab===x[0]?"active":""} onClick={()=>{setTab(x[0]);call("bw_casino_snapshot")}} key={x[0]}>{x[1]}</button>)}</nav><section className="casino-table"><div className="casino-balance"><small>AVAILABLE CASH</small><b>{money(state?.balance)}</b></div>
  {tab==="blackjack"&&<div className="blackjack"><h2>Blackwood Blackjack</h2>{game?<><div className="hand"><small>DEALER</small><div>{game.dealer.map((c,i)=><Card card={c} key={i}/>)}</div></div><div className="hand"><small>YOUR HAND · {game.player_value}</small><div>{game.player.map((c,i)=><Card card={c} key={i}/>)}</div></div><p>{game.message}</p>{game.status==="active"&&<footer><button disabled={busy} onClick={()=>call("bw_blackjack_action",{p_action:"hit"})}>Hit</button><button disabled={busy} onClick={()=>call("bw_blackjack_action",{p_action:"stand"})}>Stand</button></footer>}</>:<p>Dealer stands on 17. Blackjack pays 3:2.</p>}</div>}
  {tab==="slots"&&<div className="slots"><h2>The Three Kings</h2><div className="reels">{(state?.result?.reels||["♛","7","◆"]).map((x,i)=><i key={i}>{x}</i>)}</div><p>{state?.result?.message||"Three matching symbols pay the jackpot. Two cherries return a smaller prize."}</p></div>}
  {tab==="roulette"&&<Roulette state={state} busy={busy} bet={bet} call={call}/>} {!game&&tab!=="roulette"&&<BetControls bet={bet} setBet={setBet} busy={busy} play={play}/>}</section></div>;
}
function BetControls({bet,setBet,busy,play}){return <div className="bet-controls"><label>Stake <input type="number" min="10" max="10000" step="10" value={bet} onChange={e=>setBet(Number(e.target.value))}/></label><button disabled={busy||bet<10} onClick={play}>Place bet · {money(bet)}</button></div>}
function Roulette({state,busy,bet,call}){const [type,setType]=useState("red"),[number,setNumber]=useState(0);return <div className="roulette"><h2>European Roulette</h2><div className="wheel">{state?.result?.number??"0"}</div><p>{state?.result?.message||"One green zero. Straight numbers pay 35:1; even-money bets pay 1:1."}</p><div className="roulette-picks"><select value={type} onChange={e=>setType(e.target.value)}><option value="red">Red</option><option value="black">Black</option><option value="odd">Odd</option><option value="even">Even</option><option value="low">1–18</option><option value="high">19–36</option><option value="straight">Straight number</option></select>{type==="straight"&&<input type="number" min="0" max="36" value={number} onChange={e=>setNumber(Number(e.target.value))}/>}<button disabled={busy} onClick={()=>call("bw_roulette_spin",{p_bet:bet,p_bet_type:type,p_number:type==="straight"?number:null,p_request_id:crypto.randomUUID()})}>Spin · {money(bet)}</button></div></div>}
